#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.mongoexpress.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: {{ .Values.global.etl.port }}
        env:
        # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        #   valueFrom: 
        #     secretKeyRef:
        #       name: {{ .Values.global.hdssecret }}
        #       key: mongo-root-username
        # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.global.hdssecret }}
        #       key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.hdsconfigmap }}
              key: database_url
{{- end }}