#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.ingress.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mongo-express-ingress
  namespace: default
  labels:
    app: mongo-express
spec:
  rules:
    - host: mongo-express-aais.test.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongo-express-service
                port: 
                  number: 8081
{{- end }}