#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.mongodb.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.mongodb.servicename }}
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
{{- end }}