
DO $$
BEGIN
CREATE TABLE IF NOT EXISTS fo_class_code(
    id INT,
    code VARCHAR,
    name VARCHAR,
    type VARCHAR,
    effective_date DATE NOT NULL DEFAULT '1900-01-01',
    expiration_date DATE NOT NULL DEFAULT '9999-12-31'
);

IF NOT EXISTS (SELECT * FROM fo_class_code) THEN 
    INSERT INTO fo_class_code VALUES(1, '10', 'Computers', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(2, '15', 'Livestock -- Winter Perils (AAIS FO-324 / FO 0324 or Equivalent)', 'Livestock Perils Options (Policy Form Code 77)');
    INSERT INTO fo_class_code VALUES(3, '16', 'Livestock -- Loading and Unloading Accidents (FL-334) -- excluding sheep, Livestock -- Loading and Unloading Accidents (FL-334) - including sheep, Livestock -- Suffocation (AAIS FO-349 / FO 0349 or equivalent)', 'Livestock Perils Options (Policy Form Code 77)');
    INSERT INTO fo_class_code VALUES(4, '49', 'All other property', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(5, '51', 'Dwellings', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(6, '53', 'Silos', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(7, '54', 'Sheds, Such as Implement, Machine, and Tool', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(8, '55', 'Houses, Such as Incubator, Brooder, Milk, Hen', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(9, '56', 'Windmills and Windchargers', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(10, '58', 'Granaries', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(11, '59', 'Dairy Barns', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(12, '60', 'Hog Confinement Buildings', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(13, '61', 'Potato Houses', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(14, '62', 'Fences, Corrals, Chutes, Power and Light Poles, Wiring, Solar, Cell Towers', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(15, '64', 'Tanks', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(16, '65', 'Greenhouses', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(17, '66', 'Equipment and machinery - Tractors (Including Attachments)', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(18, '67', 'Equipment and machinery - Combines and Harvesters', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(19, '68', 'Equipment and machinery - Other Than Tractors, Combines, and Harvesters', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(20, '69', 'Equipment and machinery - Machinery Not Described', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(21, '70', 'Grain - In the Open', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(22, '71', 'Grain - Metal Structures - Threshed Grain and Seeds', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(23, '72', 'Grain - Metal Structures - General Contents', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(24, '73', 'Grain - In Other Structures', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(25, '74', 'Tobacco and Hemp', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(26, '75', 'Trays, Boxes, Box Shook', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(27, '76', 'Wool', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(28, '77', 'Barns', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(29, '78', 'Outbuildings', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(30, '99', 'All Other Structures', 'Farm Barns, Buildings, and Other Structures (Policy Form Code 10)');
    INSERT INTO fo_class_code VALUES(31, '10010', 'Baskets', 'Crafts');
    INSERT INTO fo_class_code VALUES(32, '10020', 'Candles', 'Crafts');
    INSERT INTO fo_class_code VALUES(33, '10030', 'Ceramics', 'Crafts');
    INSERT INTO fo_class_code VALUES(34, '10040', 'Decorative clothing', 'Crafts');
    INSERT INTO fo_class_code VALUES(35, '10050', 'Dolls', 'Crafts');
    INSERT INTO fo_class_code VALUES(36, '10060', 'Fabrics', 'Crafts');
    INSERT INTO fo_class_code VALUES(37, '10070', 'Flower Arrangements', 'Crafts');
    INSERT INTO fo_class_code VALUES(38, '10080', 'Glass', 'Crafts');
    INSERT INTO fo_class_code VALUES(39, '10090', 'Jewelry', 'Crafts');
    INSERT INTO fo_class_code VALUES(40, '10100', 'Metalwork', 'Crafts');
    INSERT INTO fo_class_code VALUES(41, '10110', 'Needlework', 'Crafts');
    INSERT INTO fo_class_code VALUES(42, '10120', 'Quilts', 'Crafts');
    INSERT INTO fo_class_code VALUES(43, '10130', 'Sculptures', 'Crafts');
    INSERT INTO fo_class_code VALUES(44, '10140', 'Wall Hangings', 'Crafts');
    INSERT INTO fo_class_code VALUES(45, '10150', 'Wind Chimes', 'Crafts');
    INSERT INTO fo_class_code VALUES(46, '10160', 'Wood Products', 'Crafts');
    INSERT INTO fo_class_code VALUES(47, '10170', 'Wreaths', 'Crafts');
    INSERT INTO fo_class_code VALUES(48, '20010', 'Baked Goods', 'Foods');
    INSERT INTO fo_class_code VALUES(49, '20020', 'Beverages (i.e. Coffee and Tea)', 'Foods');
    INSERT INTO fo_class_code VALUES(50, '20030', 'Candy, Nuts or Confections', 'Foods');
    INSERT INTO fo_class_code VALUES(51, '20040', 'Canning (i.e. Jellies and Jams)', 'Foods');
    INSERT INTO fo_class_code VALUES(52, '20050', 'Deli Foods', 'Foods');
    INSERT INTO fo_class_code VALUES(53, '20060', 'Fruit and Vegetable Stand (no "Pick Your Own" Operations', 'Foods');
    INSERT INTO fo_class_code VALUES(54, '20070', 'Gourmet Foods', 'Foods');
    INSERT INTO fo_class_code VALUES(55, '20080', 'Picnic Baskets', 'Foods');
    INSERT INTO fo_class_code VALUES(56, '20090', 'Smoked and Dressed Meats, Poultry, and Fish', 'Foods');
    INSERT INTO fo_class_code VALUES(57, '20100', 'Wine and Spirits', 'Foods');
    INSERT INTO fo_class_code VALUES(58, '30010', 'Accounting', 'Offices');
    INSERT INTO fo_class_code VALUES(59, '30020', 'Billing', 'Offices');
    INSERT INTO fo_class_code VALUES(60, '30030', 'Bookkeeping', 'Offices');
    INSERT INTO fo_class_code VALUES(61, '30040', 'Business Consulting', 'Offices');
    INSERT INTO fo_class_code VALUES(62, '30050', 'Calligraphy', 'Offices');
    INSERT INTO fo_class_code VALUES(63, '30060', 'Career Consulting', 'Offices');
    INSERT INTO fo_class_code VALUES(64, '30070', 'Computer Consulting', 'Offices');
    INSERT INTO fo_class_code VALUES(65, '30080', 'Counseling', 'Offices');
    INSERT INTO fo_class_code VALUES(66, '30090', 'Desktop Publishing', 'Offices');
    INSERT INTO fo_class_code VALUES(67, '30100', 'Financial Planning', 'Offices');
    INSERT INTO fo_class_code VALUES(68, '30110', 'Freelance Writing', 'Offices');
    INSERT INTO fo_class_code VALUES(69, '30120', 'Graphic Art', 'Offices');
    INSERT INTO fo_class_code VALUES(70, '30130', 'Insurance Agent', 'Offices');
    INSERT INTO fo_class_code VALUES(71, '30140', 'Mailing and Addressing', 'Offices');
    INSERT INTO fo_class_code VALUES(72, '30150', 'Public Relations', 'Offices');
    INSERT INTO fo_class_code VALUES(73, '30160', 'Real Estate Agent', 'Offices');
    INSERT INTO fo_class_code VALUES(74, '30170', 'Resume Writing', 'Offices');
    INSERT INTO fo_class_code VALUES(75, '30180', 'Telephone Answering', 'Offices');
    INSERT INTO fo_class_code VALUES(76, '30190', 'Tutoring', 'Offices');
    INSERT INTO fo_class_code VALUES(77, '30200', 'Word Processing', 'Offices');
    INSERT INTO fo_class_code VALUES(78, '40010', 'Antiques', 'Retail');
    INSERT INTO fo_class_code VALUES(79, '40020', 'Art Supplies', 'Retail');
    INSERT INTO fo_class_code VALUES(80, '40030', 'Art Work', 'Retail');
    INSERT INTO fo_class_code VALUES(81, '40040', 'Books, Magazines, and Videos', 'Retail');
    INSERT INTO fo_class_code VALUES(82, '40050', 'Candles', 'Retail');
    INSERT INTO fo_class_code VALUES(83, '40060', 'Clothing', 'Retail');
    INSERT INTO fo_class_code VALUES(84, '40070', 'Coins and Stamps', 'Retail');
    INSERT INTO fo_class_code VALUES(85, '40080', 'Collectibles', 'Retail');
    INSERT INTO fo_class_code VALUES(86, '40090', 'Cosmetics', 'Retail');
    INSERT INTO fo_class_code VALUES(87, '40100', 'Costume Jewelry', 'Retail');
    INSERT INTO fo_class_code VALUES(88, '40110', 'Decorative Housewares', 'Retail');
    INSERT INTO fo_class_code VALUES(89, '40120', 'Gifts', 'Retail');
    INSERT INTO fo_class_code VALUES(90, '40130', 'Household and Kitchen Products', 'Retail');
    INSERT INTO fo_class_code VALUES(91, '40140', 'Personal Care Products', 'Retail');
    INSERT INTO fo_class_code VALUES(92, '40150', 'Plants and Flowers', 'Retail');
    INSERT INTO fo_class_code VALUES(93, '40160', 'Stationery and Paper Products', 'Retail');
    INSERT INTO fo_class_code VALUES(94, '40170', 'Tackle and Bait', 'Retail');
    INSERT INTO fo_class_code VALUES(95, '40180', 'Toys', 'Retail');
    INSERT INTO fo_class_code VALUES(96, '40190', 'Vitamins and Health Care Products', 'Retail');
    INSERT INTO fo_class_code VALUES(97, '50010', 'Aesthetician', 'Services');
    INSERT INTO fo_class_code VALUES(98, '50020', 'Barber', 'Services');
    INSERT INTO fo_class_code VALUES(99, '50030', 'Beautician', 'Services');
    INSERT INTO fo_class_code VALUES(100, '50040', 'Bicycle Repair', 'Services');
    INSERT INTO fo_class_code VALUES(101, '50050', 'Camera Repair', 'Services');
    INSERT INTO fo_class_code VALUES(102, '50060', 'Carpet and Uphosltery Cleaning', 'Services');
    INSERT INTO fo_class_code VALUES(103, '50070', 'Clock, Jewelry, or Watch Repair', 'Services');
    INSERT INTO fo_class_code VALUES(104, '50080', 'Computer Repair', 'Services');
    INSERT INTO fo_class_code VALUES(105, '50090', 'Dog ot Cat Boarding, Breeding, or Training', 'Services');
    INSERT INTO fo_class_code VALUES(106, '50100', 'Dressmaker, Seamstress, or Tailor', 'Services');
    INSERT INTO fo_class_code VALUES(107, '50110', 'Flower Arranging', 'Services');
    INSERT INTO fo_class_code VALUES(108, '50120', 'Furniture Upholstering', 'Services');
    INSERT INTO fo_class_code VALUES(109, '50130', 'Gift Delivery Service', 'Services');
    INSERT INTO fo_class_code VALUES(110, '50140', 'Hair Stylist', 'Services');
    INSERT INTO fo_class_code VALUES(111, '50150', 'House Cleaning', 'Services');
    INSERT INTO fo_class_code VALUES(112, '50160', 'House Sitting', 'Services');
    INSERT INTO fo_class_code VALUES(113, '50170', 'Instruction (Music, Etiquette, etc.)', 'Services');
    INSERT INTO fo_class_code VALUES(114, '50180', 'Interior Decorating', 'Services');
    INSERT INTO fo_class_code VALUES(115, '50190', 'Manicurist', 'Services');
    INSERT INTO fo_class_code VALUES(116, '50200', 'Musical Instrument Repair', 'Services');
    INSERT INTO fo_class_code VALUES(117, '50210', 'Personal Shopper', 'Services');
    INSERT INTO fo_class_code VALUES(118, '50220', 'Pet Sitting and Walking', 'Services');
    INSERT INTO fo_class_code VALUES(119, '50230', 'Photography', 'Services');
    INSERT INTO fo_class_code VALUES(120, '50240', 'Picture Framing', 'Services');
    INSERT INTO fo_class_code VALUES(121, '50250', 'Printer', 'Services');
    INSERT INTO fo_class_code VALUES(122, '50260', 'Shoe Repair', 'Services');
    INSERT INTO fo_class_code VALUES(123, '50270', 'Videotaping', 'Services');
    INSERT INTO fo_class_code VALUES(124, '50280', 'Wedding or Party Planning', 'Services');
    INSERT INTO fo_class_code VALUES(125, '00', 'Does Not Apply', 'Does Not Apply');
    INSERT INTO fo_class_code VALUES(126, '01', 'Livestock', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(127, '03', 'Poultry', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(128, '04', 'Turkeys', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(129, '05', 'Hay/Straw/Fodder in buildings', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(130, '06', 'Hay/Straw/Fodder in the open', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(131, '07', 'Household contents', 'Scheduled Farm Personal Property (Policy Form Code 12)');
    INSERT INTO fo_class_code VALUES(132, '08', 'Farm products (including dairy) and supplies - NOC', 'Scheduled Farm Personal Property (Policy Form Code 12)');
END IF;
END $$;
