#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.etl.install }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: nifi
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
{{- end }}