#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.etl.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.etl.servicename }}
  namespace: nifi
spec:
  selector:
    app: nifi
  ports:
  - protocol: TCP
    targetPort: 9088
    port: 9088
    name: node-pp
  - protocol: TCP
    targetPort: 8888
    port: 8888
    name: s2s
  clusterIP: None
{{- end }}