#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.etl.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.etl.zkhsservicename }}
  namespace: nifi
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
{{- end }}