#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.etl.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.etl.zkcsservicename }}
  namespace: nifi
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
{{- end }}