#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.etl.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.etl.httpservicename }}
  namespace: nifi
spec:
  selector:
    app: nifi
  ports:
  - protocol: TCP
    targetPort: {{ .Values.global.etl.targetport }}
    port: {{ .Values.global.etl.port }}
    name: http
  type: LoadBalancer
{{- end }}