select q.state_code, q.state_name, q.territory_key,q.zip_code, q.year, 
       case when q.coverage_code = '1' then 'Bodily Injury'
              when q.coverage_code = '2' then 'Property Damage'
              when q.coverage_code = '3' then 'Single BI/PD Limit'
              when q.coverage_code = '4' then 'PIP'
              when q.coverage_code = '5' then 'Medical Payments'
              when q.coverage_code = '6' then 'Uninsured/underinsured'
              when q.coverage_code = 'X' then 'Uninsured/underinsured'
              when q.coverage_code = 'Y' then 'Uninsured/underinsured'
              when q.coverage_code = '7' and q.deductible_amount in ('0') then 'Phy Dam - Coll - FULL'
              when q.coverage_code = '8' and q.deductible_amount in ('0') then 'Phy Dam - Comp - FULL'
              when q.coverage_code = 'T' and q.deductible_amount in ('0') then 'Phy Dam - Comp - FULL'
              when q.coverage_code = '7' and q.deductible_amount in ('2') then 'Phy Dam - Coll - $100'
              when q.coverage_code = '8' and q.deductible_amount in ('2') then 'Phy Dam - Comp - $100'
              when q.coverage_code = 'T' and q.deductible_amount in ('2') then 'Phy Dam - Comp - $100'
              when q.coverage_code = '7' and q.deductible_amount in ('4') then 'Phy Dam - Coll - $250'
              when q.coverage_code = '8' and q.deductible_amount in ('4') then 'Phy Dam - Comp - $250'
              when q.coverage_code = 'T' and q.deductible_amount in ('4') then 'Phy Dam - Comp - $250'
              when q.coverage_code = '7' and q.deductible_amount in ('5') then 'Phy Dam - Coll - $500'
              when q.coverage_code = '8' and q.deductible_amount in ('5') then 'Phy Dam - Comp - $500'
              when q.coverage_code = 'T' and q.deductible_amount in ('5') then 'Phy Dam - Comp - $500'
              when q.coverage_code = '7' and q.deductible_amount in ('6') then 'Phy Dam - Coll - $1000'
              when q.coverage_code = '8' and q.deductible_amount in ('6') then 'Phy Dam - Comp - $1000'
              when q.coverage_code = 'T' and q.deductible_amount in ('6') then 'Phy Dam - Comp - $1000'
              when q.coverage_code = '7' and q.deductible_amount not in ('0', '2', '4', '5', '6') then 'Phy Dam - Coll - ALL OTHER'
              when q.coverage_code = '8' and q.deductible_amount not in ('0', '2', '4', '5', '6') then 'Phy Dam - Comp - ALL OTHER'
              when q.coverage_code = 'T' and q.deductible_amount not in ('0', '2', '4', '5', '6') then 'Phy Dam - Comp - ALL OTHER'              
              when q.coverage_code = '9' then 'Bodily Injury'
              else null end as coverage,
              from 