create table au_premium
(
LineOfBusiness VARCHAR ( 255 ),
Subline VARCHAR ( 255 ),
SublineCategory VARCHAR ( 255 ),
AccountingDate TIMESTAMP,
CompanyCode VARCHAR ( 255 ),
CompanyID VARCHAR ( 255 ),
State VARCHAR ( 55 ),
Territory INT,
OptionalZipCodeIndicator VARCHAR ( 255 ),
PremiumAmount INT,
Program VARCHAR ( 255 ),
EffectiveDate TIMESTAMP,
ExpirationDate TIMESTAMP,
PolicyIdentifier VARCHAR ( 255 ),
AccountingTermExpiration TIMESTAMP,
NCProgramEnhancement VARCHAR ( 25 ),
ZipCode INT,
ZipCodeSuffix VARCHAR ( 255 ),
MonthlyPremiumAmount INT,
CoverageCategory VARCHAR ( 255 ),
Coverage VARCHAR ( 255 ),
CoverageCode INT,
LiabilityLimitsName VARCHAR ( 255 ),
LiabilityLimitsAmount VARCHAR ( 255 ) ,
DeductibleCode VARCHAR ( 255 ),
Exposure INT,
MonthsCovered INT,
SingleMultiCarRating VARCHAR ( 255 ),
Terrorism VARCHAR ( 5 ),
Packaging VARCHAR ( 255 ),
PoolAffiliation VARCHAR ( 255 ),
UMUIMStacking VARCHAR ( 5 ),
PassiveRestraintDiscount VARCHAR ( 255 ),
AntiLockBrakesDiscount VARCHAR ( 255 ),
DefensiveDriverDiscount VARCHAR ( 255 ),
OperatorAge VARCHAR ( 255 ),
OperatorAgeCode INT,
Gender VARCHAR ( 255 ),
MaritalStatus VARCHAR ( 255 ),
MaritalStatusCode INT,
PrincipalSecondary VARCHAR ( 5 ),
DriversTraining VARCHAR ( 5 ),
GoodStudentDiscount VARCHAR ( 5 ),
PenaltyPoints INT,
VehicleUse VARCHAR ( 255 ),
VehicleUseOperator VARCHAR ( 255 ),
CommuteDistance VARCHAR ( 255 ),
AnnualDistance VARCHAR ( 255 ),
VehiclePerformance VARCHAR ( 255 ),
BodyStyle VARCHAR ( 255 ),
BodySize VARCHAR ( 255 ),
ModelYear INT,
Symbol INT
);