do $$ 
begin
create table if not exists pa_anti_theft_device_discount_code (
    id int,
    code varchar,
    description varchar,
    fk_state_id int,
);

if not exists (select * from pa_anti_theft_device_discount_code) then
insert into pa_anti_theft_device_discount_code values ( 1,1,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 2,1,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 3,1,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 4,1,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 5,1,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 6,1,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 7,1,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 8,2,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 9,2,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 10,2,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 11,2,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 12,2,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 13,2,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 14,2,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 15,3,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 16,3,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 17,3,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 18,3,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 19,3,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 20,3,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 21,3,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 22,4,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 23,4,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 24,4,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 25,4,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 26,4,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 27,4,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 28,4,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 29,5,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 30,5,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 31,5,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 32,5,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 33,5,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 34,5,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 35,5,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 36,6,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 37,6,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 38,6,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 39,6,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 40,6,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 41,6,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 42,6,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 43,7,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 44,7,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 45,7,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 46,7,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 47,7,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 48,7,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 49,7,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 50,8,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 51,8,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 52,8,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 53,8,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 54,8,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 55,8,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 56,8,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 57,9,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 58,9,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 59,9,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 60,9,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 61,9,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 62,9,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 63,9,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 64,10,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 65,10,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 66,10,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 67,10,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 68,10,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 69,10,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 70,10,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 71,11,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 72,11,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 73,11,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 74,11,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 75,11,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 76,11,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 77,11,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 78,12,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 79,12,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 80,12,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 81,12,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 82,12,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 83,12,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 84,12,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 85,13,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 86,13,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 87,13,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 88,13,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 89,13,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 90,13,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 91,13,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 92,14,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 93,14,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 94,14,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 95,14,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 96,14,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 97,14,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 98,14,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 99,15,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 100,15,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 101,15,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 102,15,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 103,15,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 104,15,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 105,15,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 106,16,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 107,16,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 108,16,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 109,16,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 110,16,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 111,16,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 112,16,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 113,17,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 114,17,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 115,17,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 116,17,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 117,17,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 118,17,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 119,17,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 120,18,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 121,18,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 122,18,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 123,18,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 124,18,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 125,18,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 126,18,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 127,19,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 128,19,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 129,19,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 130,19,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 131,19,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 132,19,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 133,19,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 134,20,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 135,20,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 136,20,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 137,20,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 138,20,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 139,20,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 140,20,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 141,21,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 142,21,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 143,21,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 144,21,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 145,21,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 146,21,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 147,21,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 148,22,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 149,22,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 150,22,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 151,22,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 152,22,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 153,22,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 154,22,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 155,23,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 156,23,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 157,23,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 158,23,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 159,23,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 160,23,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 161,23,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 162,24,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 163,24,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 164,24,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 165,24,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 166,24,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 167,24,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 168,24,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 169,25,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 170,25,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 171,25,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 172,25,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 173,25,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 174,25,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 175,25,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 176,26,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 177,26,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 178,26,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 179,26,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 180,26,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 181,26,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 182,26,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 183,27,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 184,27,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 185,27,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 186,27,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 187,27,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 188,27,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 189,27,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 190,28,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 191,28,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 192,28,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 193,28,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 194,28,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 195,28,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 196,28,'99','All other (Vehicles not rated under a discount program)');
-- NJ = 29
insert into pa_anti_theft_device_discount_code values ( 197,29,'01','Vehicle qualifies for discount under Category I');
insert into pa_anti_theft_device_discount_code values ( 198,29,'02','Vehicle qualifies for discount under Category II');
insert into pa_anti_theft_device_discount_code values ( 199,29,'03','Vehicle qualifies for discount under Category III');
insert into pa_anti_theft_device_discount_code values ( 200,29,'04','Vehicle qualifies for discount under Category IV');
insert into pa_anti_theft_device_discount_code values ( 201,29,'05','Vehicle qualifies for discount under Category III and IV');
insert into pa_anti_theft_device_discount_code values ( 203,29,'09','Vehicle without an anti-theft device (no discount);');


insert into pa_anti_theft_device_discount_code values ( 204,30,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 205,30,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 206,30,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 207,30,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 208,30,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 209,30,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 210,30,'99','All other (Vehicles not rated under a discount program)');

-- NY = 31
insert into pa_anti_theft_device_discount_code values ( 211,31,'01','Vehicles with no discount');
insert into pa_anti_theft_device_discount_code values ( 212,31,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 213,31,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 214,31,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 215,31,'05','Vehicles with electronic homing devices only — with discount');
insert into pa_anti_theft_device_discount_code values ( 216,31,'10','Vehicles with VIN etched window glass only — with discount');
insert into pa_anti_theft_device_discount_code values ( 216,31,'11','With discount less than the maximum reduction of 25% per vehicle');
insert into pa_anti_theft_device_discount_code values ( 216,31,'10','With discount equal to the maximum reduction of 25% per vehicle');


insert into pa_anti_theft_device_discount_code values ( 218,32,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 219,32,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 220,32,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 221,32,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 222,32,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 223,32,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 224,32,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 225,33,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 226,33,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 227,33,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 228,33,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 229,33,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 230,33,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 231,33,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 232,34,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 233,34,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 234,34,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 235,34,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 236,34,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 237,34,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 238,34,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 239,35,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 240,35,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 241,35,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 242,35,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 243,35,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 244,35,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 245,35,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 246,36,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 247,36,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 248,36,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 249,36,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 250,36,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 251,36,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 252,36,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 253,37,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 254,37,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 255,37,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 256,37,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 257,37,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 258,37,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 259,37,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 260,38,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 261,38,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 262,38,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 263,38,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 264,38,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 265,38,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 266,38,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 267,39,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 268,39,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 269,39,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 270,39,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 271,39,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 272,39,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 273,39,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 274,40,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 275,40,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 276,40,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 277,40,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 278,40,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 279,40,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 280,40,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 281,41,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 282,41,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 283,41,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 284,41,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 285,41,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 286,41,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 287,41,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 288,42,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 289,42,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 290,42,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 291,42,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 292,42,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 293,42,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 294,42,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 295,43,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 296,43,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 297,43,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 298,43,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 299,43,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 300,43,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 301,43,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 302,44,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 303,44,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 304,44,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 305,44,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 306,44,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 307,44,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 308,44,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 309,45,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 310,45,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 311,45,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 312,45,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 313,45,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 314,45,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 315,45,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 316,46,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 317,46,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 318,46,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 319,46,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 320,46,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 321,46,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 322,46,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 323,47,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 324,47,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 325,47,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 326,47,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 327,47,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 328,47,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 329,47,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 330,48,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 331,48,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 332,48,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 333,48,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 334,48,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 335,48,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 336,48,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 337,49,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 338,49,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 339,49,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 340,49,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 341,49,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 342,49,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 343,49,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 344,50,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 345,50,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 346,50,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 347,50,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 348,50,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 349,50,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 350,50,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 351,51,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 352,51,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 353,51,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 354,51,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 355,51,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 356,51,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 357,51,'99','All other (Vehicles not rated under a discount program)');
insert into pa_anti_theft_device_discount_code values ( 358,52,'01','Vehicles with no discount but rated under a discount program');
insert into pa_anti_theft_device_discount_code values ( 359,52,'02','Vehicles with alarm only — with discount');
insert into pa_anti_theft_device_discount_code values ( 360,52,'03','Vehicles with active devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 361,52,'04','Vehicles with passive devices — with discount');
insert into pa_anti_theft_device_discount_code values ( 362,52,'05','Vehicles with an alarm and an active device — with discount');
insert into pa_anti_theft_device_discount_code values ( 363,52,'06','Vehicles with an alarm and a passive device — with discount');
insert into pa_anti_theft_device_discount_code values ( 364,52,'99','All other (Vehicles not rated under a discount program)');
end if;

end $$