CREATE TABLE STATSGT2.pa_stat_stg(
ID INT NOT NULL AUTO_INCREMENT,
TRANSMITTAL_ID INT NOT NULL,
CHANGE_COMMENTS VARCHAR(4000) DEFAULT NULL,
UPDATED_BY INT DEFAULT NULL,
EFF_START_DATE DATETIME(6) DEFAULT NULL, 
EFF_END_DATE DATETIME(6) NOT NULL,
LAST_VALIDATED_DATE DATETIME(6) DEFAULT NULL,
REP_YR_4DIGIT DECIMAL(4,0) DEFAULT NULL,
LINE VARCHAR(2) DEFAULT NULL, --Line of Insurance
REP_MO VARCHAR(2) DEFAULT NULL, --Accounting Date
REP_YR VARCHAR(1) DEFAULT NULL, --Accounting Date
COMP VARCHAR(4) DEFAULT NULL, --company code
STATE VARCHAR(2) DEFAULT NULL, --State Code
TERRITORY VARCHAR(3) DEFAULT NULL, --Territory
TRANS VARCHAR(1) DEFAULT NULL, --Transaction Code
PREM_AMT DECIMAL(12,2) DEFAULT NULL, --Premium Amount
LOSS_AMT DECIMAL(12,2) DEFAULT NULL, --Loss Amount
PROG_CD VARCHAR(1) DEFAULT NULL, --Program Code
COV_CODE VARCHAR(1) DEFAULT NULL, --Coverage Code
SUBLINE VARCHAR(1) DEFAULT NULL, --Subline
RES030 VARCHAR(4) DEFAULT NULL,
AGE VARCHAR(1) DEFAULT NULL, --Operators Age
SEX_MARITAL VARCHAR(1) DEFAULT NULL, --sex & marital status
VEHICLE_USE VARCHAR(1) DEFAULT NULL, --vehicle use
VEHICLE_PERF VARCHAR(1) DEFAULT NULL, --vehicle performance
COMMERCIAL_CLASS VARCHAR(1) DEFAULT NULL, 
DRIV_TRAIN_GOOD_STUDENT VARCHAR(1) DEFAULT NULL, --training
COMMERCIAL_USE VARCHAR(1) DEFAULT NULL,
PENALTY_POINTS VARCHAR(1) DEFAULT NULL, --penalty points
LIA_LIM VARCHAR(1) DEFAULT NULL, --liability limit
DED_AMT VARCHAR(1) DEFAULT NULL, --deductible
BODY_STYLE VARCHAR(2) DEFAULT NULL, --vehicle class
BODY_SIZE VARCHAR(1) DEFAULT NULL, --vehicle class
MODEL_YEAR VARCHAR(2) DEFAULT NULL, --model year
UM_UIM_MOTORIST VARCHAR(1) DEFAULT NULL, --unins/underins motorist
EXPOSURE INT DEFAULT NULL, --exposure
CLM_CNT INT DEFAULT NULL, --claim count
COL VARCHAR(1) DEFAULT NULL, --cause of loss
MOS_COV VARCHAR(2) DEFAULT NULL, --months covered
RES050 VARCHAR(1) DEFAULT NULL,
TERRORISM VARCHAR(1) DEFAULT NULL, --terrorism indicator
RES051 VARCHAR(1) DEFAULT NULL,
RES052 VARCHAR(4) DEFAULT NULL,
SING_MULT_CAR VARCHAR(1) DEFAULT NULL, --single/multi car
ACCIDENT_MON VARCHAR(2) DEFAULT NULL, --accident date
RES057 VARCHAR(3) DEFAULT NULL,
ACCIDENT_YR VARCHAR(2) DEFAULT NULL, --accident date
RES060 VARCHAR(4) DEFAULT NULL,
PACKAGE_ID VARCHAR(1) DEFAULT NULL, --package identification
POOL VARCHAR(1) DEFAULT NULL, --pool affiliation
CLAIM_NUM VARCHAR(12) DEFAULT NULL, --claim number/occurance identification
POLICY_NUM VARCHAR(14) DEFAULT NULL, --policy identification
CLAIM_ID VARCHAR(2) DEFAULT NULL, --claim id
--NC PROGRAM ENHANCEMENT???
RES080 VARCHAR(1) DEFAULT NULL,
ZIP VARCHAR(5) DEFAULT NULL, --zip code
ZIP_SUFF VARCHAR(4) DEFAULT NULL, --optional zip code suffix
UM_UIM_STACK_IND VARCHAR(1) DEFAULT NULL, --um/uim stacking indicator
RES091 VARCHAR(2) DEFAULT NULL,
SYMBOL VARCHAR(2) DEFAULT NULL, --symbol code
PASS_RESTRAINT VARCHAR(1) DEFAULT NULL, --passive restraint
ANTI_LOCK VARCHAR(1) DEFAULT NULL, --anti-lock breaks
ANTI_THEFT VARCHAR(2) DEFAULT NULL, --anti-theft device
DEF_DRIVER VARCHAR(1) DEFAULT NULL, --defensive driver
PIP_LIMIT_DED VARCHAR(1) DEFAULT NULL, --pip limits/ded.
NJ_PIP_LIMIT VARCHAR(2) DEFAULT NULL, --NJ pip limits
RES099 VARCHAR(2) DEFAULT NULL,
NJ_PIP_DED VARCHAR(1) DEFAULT NULL, --NJ deductible
RAT_TERM_ZONE VARCHAR(3) DEFAULT NULL, --rating/ terminal zone
RES101 VARCHAR(3) DEFAULT NULL,
ASSIGN_RISK_RATE_CLASS VARCHAR(4) DEFAULT NULL, --assigned risk (rate class code)
ASSIGN_RISK_PTS_SUR VARCHAR(2) DEFAULT NULL, --assigned risk (penalty points/percent of surcharge code)
EXP_RATING_MOD VARCHAR(3) DEFAULT NULL, --experience rating modification factor
RES110 VARCHAR(3) DEFAULT NULL,
RES113 VARCHAR(1) DEFAULT NULL,
EXCEPT_A VARCHAR(2) DEFAULT NULL, --exception code A
EXCEPT_B VARCHAR(2) DEFAULT NULL, --exception code B
EXCEPT_C VARCHAR(2) DEFAULT NULL, --exception code C
EXCEPT_D VARCHAR(2) DEFAULT NULL, --exception code D
RES122 VARCHAR(15) DEFAULT NULL,
COUNTY VARCHAR(3) DEFAULT NULL,
CO_USE VARCHAR(11) DEFAULT NULL,
STATUS VARCHAR(20) DEFAULT NULL,
LINE_NUMBER INT DEFAULT NULL,
NOTES VARCHAR(4000) DEFAULT NULL,
VERSION INT  DEFAULT '1',
VAL_VER INT  DEFAULT '1',
VIN VARCHAR(17) DEFAULT NULL,
LIMIT_LOSS_CD_ID VARCHAR(1) DEFAULT NULL, --limit coding loss ID
RES111 VARCHAR(2) DEFAULT NULL,
OPT_ZIP_CD_IND VARCHAR(1) DEFAULT NULL, --Optional Zip Code Indicator
PRIMARY KEY (ID),
FOREIGN KEY (TRANSMITTAL_ID) REFERENCES TRANSMITTAL(ID)
);
