
DO $$ 
BEGIN
CREATE TABLE IF NOT EXISTS ho_loss_settlement_indicator_code (
    id INT,
    code VARCHAR,
    description VARCHAR,
    type VARCHAR,
    effective_date DATE NOT NULL DEFAULT '1900-01-01',
    expiration_date DATE NOT NULL DEFAULT '9999-12-31'
);

IF NOT EXISTS (SELECT * FROM ho_loss_settlement_indicator_code) THEN 
    INSERT INTO ho_loss_settlement_indicator_code VALUES(1,'0','No modifications to loss settlement terms of underlying policy OR Does Not Apply','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(2,'3','Functional Replacement Cost Coverage OR Repair Cost Terms (Coverages A and B) | AAIS Endorsement ML-255, ML 0255, HO 0255, HO 4857, or equivalent | ISO Endorsement HO 05 30, HO 23 89 MI, or equivalent','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(3,'4','Modified Replacement Cost Terms or Special Loss Settlement Endorsement | AAIS Endorsement ML-256, ML 0256, HO 0256, HO 4856, or equivalent | ISO Endorsement HO 04 56 or equivalent','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(4,'6','Actual Cash Value Coverage (Coverages A and B) | AAIS Form ML-1 under AAIS Standard HO Program (1978 edition ML forms) | AAIS Form ML-1 under AAIS Expanded HO Program (1988 edition ML forms) | AAIS Endorsement ML-15, ML 0015, HO 0015, HO 4815, or equivalent | ISO Endorsement HO 04 81 or equivalent','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(5,'A','Expanded Replacement Cost (Coverage A only) -- not applicable to ISO Program | AAIS Endorsement ML-145, ML 0145, or equivalent','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(6,'F','Actual Cash Value Loss Settlement - Windstorm or Hail Losses to Roof Surfacing | AAIS Endorsement HO 4835 or equivalent | ISO Endorsement HO 04 93 or equivalent','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(7,'B','Specified Additional Amount of Insurance (Coverage A) AAIS Endorsement HO 0444, HO 4844, or equivalent | ISO Endorsement HO 04 20 or equivalent | > At 25% of Coverage A limit','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(8,'C','Specified Additional Amount of Insurance (Coverage A) AAIS Endorsement HO 0444, HO 4844, or equivalent | ISO Endorsement HO 04 20 or equivalent | > At 50% of Coverage A limit','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(9,'D','Specified Additional Amount of Insurance (Coverage A) AAIS Endorsement HO 0444, HO 4844, or equivalent | ISO Endorsement HO 04 20 or equivalent | > Other than 25% or 50% of Coverage A limit','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(10,'E','Additional Limits (Coverages A, B, C, and D) | AAIS Endorsement HO 0443, HO 4843, or equivalent | ISO Endorsement HO 04 11 or equivalent','Modification to Coverage A (building), but not to Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(11,'0','No modifications to loss settlement terms of underlying policy OR Does Not Apply','Modification to Coverage C (personal property), but not to Coverage A (building)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(12,'7','Replacement Value (Coverage C - Personal Property) | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO-290 or HO 04 90 or equivalent','Modification to Coverage C (personal property), but not to Coverage A (building)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(13,'0','No modifications to loss settlement terms of underlying policy OR Does Not Apply','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(14,'G','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Functional Replacement Cost Coverage OR Repair Cost Terms (Coverages A and B) | AAIS Endorsement ML-255, ML 0255, HO 0255, HO 4857, or equivalent | ISO Endorsement HO 05 30, HO 23 89 MI, or equivalent','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(15,'J','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Expanded Replacement Cost (Coverage A only) -- not applicable to ISO Program | AAIS Endorsement ML-145, ML 0145, or equivalent','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(16,'P','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Actual Cash Value Coverage (Coverages A and B) | AAIS Form ML-1 under AAIS Standard HO Program (1978 edition ML forms) | AAIS Form ML-1 under AAIS Expanded HO Program (1988 edition ML forms) | AAIS Endorsement ML-15, ML 0015, HO 0015, HO 4815, or equivalent | ISO Endorsement HO 04 81 or equivalent','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(17,'R','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Actual Cash Value Loss Settlement - Windstorm or Hail Losses to Roof Surfacing | AAIS Endorsement HO 4835 or equivalent | ISO Endorsement HO 04 93 or equivalent','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(18,'H','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Modified Replacement Cost Terms or Special Loss Settlement Endorsement | AAIS Endorsement ML-256, ML 0256, HO 0256, HO 4856, or equivalent | ISO Endorsement HO 04 56 or equivalent','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(19,'K','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Specified Additional Amount of Insurance (Coverage A) | AAIS Endorsement HO 0444, HO 4844, or equivalent | ISO Endorsement HO 04 20 or equivalent | > At 25% of Coverage A limit','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(20,'L','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Specified Additional Amount of Insurance (Coverage A) | AAIS Endorsement HO 0444, HO 4844, or equivalent | ISO Endorsement HO 04 20 or equivalent | > At 50% of Coverage A limit','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(21,'M','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Specified Additional Amount of Insurance (Coverage A) | AAIS Endorsement HO 0444, HO 4844, or equivalent | ISO Endorsement HO 04 20 or equivalent | > Other than 25% or 50% of Coverage A limit','Modifications to both Coverage A (building) and Coverage C (personal property)');
    INSERT INTO ho_loss_settlement_indicator_code VALUES(22,'N','With Replacement Cost on Coverage C | AAIS Endorsement ML-55, ML 0055, HO 0055, HO 4855, or equivalent | ISO Endorsement HO 290, HO 0490, or equivalent AND Additional Limits (Coverages A, B, C, and D) | AAIS Endorsement HO 0443, HO 4843, or equivalent | ISO Endorsement HO 04 11 or equivalent','Modifications to both Coverage A (building) and Coverage C (personal property)');
END IF;
END $$;
