function getMobileHomeownerPolicy(companyId){
    sql = `CREATE TABLE openidl_base_${companyId}.mho_policy
    (
        id SERIAL PRIMARY KEY,
        line_of_insurance VARCHAR,
        accounting_date DATE,
        company_code VARCHAR,
        company_ID VARCHAR,
        state_code VARCHAR,
        county_code VARCHAR,
        area_indicator VARCHAR,
        territory VARCHAR,
        record_type VARCHAR,
        transaction_type VARCHAR,
        transaction_code VARCHAR,
        premium_amount Numeric (20,6),
        monthly_premium_amount Numeric (20,6),
        exposure VARCHAR,
        annual_statement_line VARCHAR,
        program VARCHAR,
        policy_form VARCHAR,
        policy_category VARCHAR,
        policy_type VARCHAR,
        reporting_form VARCHAR,
        reporting_category VARCHAR,
        loss_settlement_indicator VARCHAR,
        loss_settlement_indicator_description VARCHAR,
        accounting_term_expiration DATE,
        primary_property_amount Numeric (20,6),
        deductible_type VARCHAR,
        deductible_amount VARCHAR,
        wind_hail_deductible VARCHAR,
        class_code VARCHAR,
        class_code_name VARCHAR,
        class_code_type VARCHAR,
        class_code_category VARCHAR,
        class_code_subcategory VARCHAR,
        class_code_watercraft_size VARCHAR,
        class_code_engine_size VARCHAR,
        fire_code VARCHAR,
        fire_code_name VARCHAR,
        fire_code_type VARCHAR,
        fire_code_category VARCHAR,
        year_of_manufacture VARCHAR,
        liability_limit VARCHAR,
        medical_payments VARCHAR,
        es_liq_fuel_prop VARCHAR,
        es_liq_fuel_prop_name VARCHAR,
        es_liq_fuel_prop_type VARCHAR,
        es_liq_fuel_liab VARCHAR,
        es_liq_fuel_liab_name VARCHAR,
        es_liq_fuel_liab_type VARCHAR,
        occupancy_code VARCHAR,
        occupancy_code_name VARCHAR,
        occupancy_code_type VARCHAR,
        hbb_indicator VARCHAR,
        hbb_indicator_description VARCHAR,
        tie_down_code VARCHAR,
        tie_down VARCHAR,
        ordinance_or_law_coverage VARCHAR,
        theft_deductible_amount VARCHAR,
        sec_prop_amt_of_insurance VARCHAR,
        mold_damage_coverage VARCHAR,
        mold_damage_coverage_property VARCHAR,
        mold_damage_coverage_liability VARCHAR,
        mold_damage_coverage_notes VARCHAR,
        pool_code VARCHAR,
        pool_code_description VARCHAR,
        months_covered Numeric (20,6),
        zip_code VARCHAR,
        zip_code_suffix VARCHAR,
        policy_number VARCHAR
    );`
    return sql
}

module.exports = getMobileHomeownerPolicy
