insert into pa_coverage_code values(1,'1',1,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(2,'2',1,'Property Damage Liability','Liability');
insert into pa_coverage_code values(3,'3',1,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(4,'4',1,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(5,'5',1,'Medical Payments','Liability');
insert into pa_coverage_code values(6,'6',1,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(7,'7',1,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(8,'8',1,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(9,'9',1,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(10,'X',1,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(11,'Y',1,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(12,'T',1,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(13,'H',1,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(14,'W',1,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(15,'Z',1,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(16,'1',2,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(17,'2',2,'Property Damage Liability','Liability');
insert into pa_coverage_code values(18,'3',2,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(19,'4',2,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(20,'5',2,'Medical Payments','Liability');
insert into pa_coverage_code values(21,'6',2,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(22,'7',2,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(23,'8',2,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(24,'9',2,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(25,'X',2,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(26,'Y',2,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(27,'T',2,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(28,'H',2,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(29,'W',2,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(30,'Z',2,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(31,'1',4,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(32,'2',4,'Property Damage Liability','Liability');
insert into pa_coverage_code values(33,'3',4,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(34,'4',4,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(35,'5',4,'Medical Payments','Liability');
insert into pa_coverage_code values(36,'6',4,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(37,'7',4,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(38,'8',4,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(39,'9',4,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(40,'X',4,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(41,'Y',4,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(42,'T',4,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(43,'H',4,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(44,'W',4,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(45,'Z',4,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(46,'1',5,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(47,'2',5,'Property Damage Liability','Liability');
insert into pa_coverage_code values(48,'3',5,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(49,'4',5,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(50,'5',5,'Medical Payments','Liability');
insert into pa_coverage_code values(51,'6',5,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(52,'7',5,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(53,'8',5,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(54,'9',5,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(55,'X',5,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(56,'Y',5,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(57,'T',5,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(58,'H',5,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(59,'W',5,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(60,'Z',5,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(61,'1',6,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(62,'2',6,'Property Damage Liability','Liability');
insert into pa_coverage_code values(63,'3',6,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(64,'4',6,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(65,'5',6,'Medical Payments','Liability');
insert into pa_coverage_code values(66,'6',6,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(67,'7',6,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(68,'8',6,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(69,'9',6,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(70,'X',6,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(71,'Y',6,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(72,'T',6,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(73,'H',6,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(74,'W',6,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(75,'Z',6,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(76,'1',7,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(77,'2',7,'Property Damage Liability','Liability');
insert into pa_coverage_code values(78,'3',7,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(79,'4',7,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(80,'5',7,'Medical Payments','Liability');
insert into pa_coverage_code values(81,'6',7,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(82,'7',7,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(83,'8',7,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(84,'9',7,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(85,'X',7,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(86,'Y',7,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(87,'T',7,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(88,'H',7,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(89,'W',7,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(90,'Z',7,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(91,'1',8,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(92,'2',8,'Property Damage Liability','Liability');
insert into pa_coverage_code values(93,'3',8,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(94,'4',8,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(95,'5',8,'Medical Payments','Liability');
insert into pa_coverage_code values(96,'6',8,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(97,'7',8,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(98,'8',8,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(99,'9',8,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(100,'X',8,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(101,'Y',8,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(102,'T',8,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(103,'H',8,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(104,'W',8,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(105,'Z',8,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(106,'1',9,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(107,'2',9,'Property Damage Liability','Liability');
insert into pa_coverage_code values(108,'3',9,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(109,'4',9,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(110,'5',9,'Medical Payments','Liability');
insert into pa_coverage_code values(111,'6',9,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(112,'7',9,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(113,'8',9,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(114,'9',9,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(115,'X',9,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(116,'Y',9,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(117,'T',9,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(118,'H',9,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(119,'W',9,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(120,'Z',9,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(121,'1',10,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(122,'2',10,'Property Damage Liability','Liability');
insert into pa_coverage_code values(123,'3',10,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(124,'4',10,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(125,'5',10,'Medical Payments','Liability');
insert into pa_coverage_code values(126,'6',10,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(127,'7',10,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(128,'8',10,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(129,'9',10,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(130,'X',10,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(131,'Y',10,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(132,'T',10,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(133,'H',10,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(134,'W',10,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(135,'Z',10,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(136,'1',11,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(137,'2',11,'Property Damage Liability','Liability');
insert into pa_coverage_code values(138,'3',11,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(139,'4',11,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(140,'5',11,'Medical Payments','Liability');
insert into pa_coverage_code values(141,'6',11,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(142,'7',11,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(143,'8',11,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(144,'9',11,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(145,'X',11,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(146,'Y',11,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(147,'T',11,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(148,'H',11,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(149,'W',11,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(150,'Z',11,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(151,'1',12,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(152,'2',12,'Property Damage Liability','Liability');
insert into pa_coverage_code values(153,'3',12,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(154,'4',12,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(155,'5',12,'Medical Payments','Liability');
insert into pa_coverage_code values(156,'6',12,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(157,'7',12,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(158,'8',12,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(159,'9',12,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(160,'X',12,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(161,'Y',12,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(162,'T',12,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(163,'H',12,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(164,'W',12,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(165,'Z',12,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(166,'1',13,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(167,'2',13,'Property Damage Liability','Liability');
insert into pa_coverage_code values(168,'3',13,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(169,'4',13,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(170,'5',13,'Medical Payments','Liability');
insert into pa_coverage_code values(171,'6',13,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(172,'7',13,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(173,'8',13,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(174,'9',13,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(175,'X',13,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(176,'Y',13,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(177,'T',13,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(178,'H',13,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(179,'W',13,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(180,'Z',13,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(181,'1',14,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(182,'2',14,'Property Damage Liability','Liability');
insert into pa_coverage_code values(183,'3',14,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(184,'4',14,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(185,'5',14,'Medical Payments','Liability');
insert into pa_coverage_code values(186,'6',14,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(187,'7',14,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(188,'8',14,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(189,'9',14,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(190,'X',14,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(191,'Y',14,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(192,'T',14,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(193,'H',14,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(194,'W',14,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(195,'Z',14,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(196,'1',15,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(197,'2',15,'Property Damage Liability','Liability');
insert into pa_coverage_code values(198,'3',15,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(199,'4',15,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(200,'5',15,'Medical Payments','Liability');
insert into pa_coverage_code values(201,'6',15,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(202,'7',15,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(203,'8',15,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(204,'9',15,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(205,'X',15,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(206,'Y',15,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(207,'T',15,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(208,'H',15,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(209,'W',15,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(210,'Z',15,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(211,'1',16,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(212,'2',16,'Property Damage Liability','Liability');
insert into pa_coverage_code values(213,'3',16,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(214,'4',16,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(215,'5',16,'Medical Payments','Liability');
insert into pa_coverage_code values(216,'6',16,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(217,'7',16,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(218,'8',16,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(219,'9',16,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(220,'X',16,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(221,'Y',16,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(222,'T',16,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(223,'H',16,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(224,'W',16,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(225,'Z',16,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(226,'1',17,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(227,'2',17,'Property Damage Liability','Liability');
insert into pa_coverage_code values(228,'3',17,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(229,'4',17,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(230,'5',17,'Medical Payments','Liability');
insert into pa_coverage_code values(231,'6',17,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(232,'7',17,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(233,'8',17,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(234,'9',17,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(235,'X',17,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(236,'Y',17,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(237,'T',17,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(238,'H',17,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(239,'W',17,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(240,'Z',17,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(241,'1',18,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(242,'2',18,'Property Damage Liability','Liability');
insert into pa_coverage_code values(243,'3',18,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(244,'4',18,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(245,'5',18,'Medical Payments','Liability');
insert into pa_coverage_code values(246,'6',18,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(247,'7',18,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(248,'8',18,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(249,'9',18,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(250,'X',18,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(251,'Y',18,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(252,'T',18,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(253,'H',18,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(254,'W',18,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(255,'Z',18,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(256,'1',19,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(257,'2',19,'Property Damage Liability','Liability');
insert into pa_coverage_code values(258,'3',19,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(259,'4',19,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(260,'5',19,'Medical Payments','Liability');
insert into pa_coverage_code values(261,'6',19,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(262,'7',19,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(263,'8',19,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(264,'9',19,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(265,'X',19,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(266,'Y',19,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(267,'T',19,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(268,'H',19,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(269,'W',19,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(270,'Z',19,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(271,'1',20,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(272,'2',20,'Property Damage Liability','Liability');
insert into pa_coverage_code values(273,'3',20,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(274,'4',20,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(275,'5',20,'Medical Payments','Liability');
insert into pa_coverage_code values(276,'6',20,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(277,'7',20,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(278,'8',20,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(279,'9',20,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(280,'X',20,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(281,'Y',20,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(282,'T',20,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(283,'H',20,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(284,'W',20,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(285,'Z',20,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(286,'1',21,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(287,'2',21,'Property Damage Liability','Liability');
insert into pa_coverage_code values(288,'3',21,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(289,'4',21,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(290,'5',21,'Medical Payments','Liability');
insert into pa_coverage_code values(291,'6',21,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(292,'7',21,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(293,'8',21,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(294,'9',21,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(295,'X',21,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(296,'Y',21,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(297,'T',21,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(298,'H',21,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(299,'W',21,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(300,'Z',21,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(301,'1',22,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(302,'2',22,'Property Damage Liability','Liability');
insert into pa_coverage_code values(303,'3',22,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(304,'4',22,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(305,'5',22,'Medical Payments','Liability');
insert into pa_coverage_code values(306,'6',22,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(307,'7',22,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(308,'8',22,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(309,'9',22,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(310,'X',22,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(311,'Y',22,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(312,'T',22,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(313,'H',22,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(314,'W',22,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(315,'Z',22,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(316,'1',23,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(317,'2',23,'Property Damage Liability','Liability');
insert into pa_coverage_code values(318,'3',23,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(319,'4',23,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(320,'5',23,'Medical Payments','Liability');
insert into pa_coverage_code values(321,'6',23,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(322,'7',23,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(323,'8',23,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(324,'9',23,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(325,'X',23,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(326,'Y',23,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(327,'T',23,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(328,'H',23,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(329,'W',23,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(330,'Z',23,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(331,'1',24,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(332,'2',24,'Property Damage Liability','Liability');
insert into pa_coverage_code values(333,'3',24,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(334,'4',24,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(335,'5',24,'Medical Payments','Liability');
insert into pa_coverage_code values(336,'6',24,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(337,'7',24,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(338,'8',24,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(339,'9',24,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(340,'X',24,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(341,'Y',24,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(342,'T',24,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(343,'H',24,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(344,'W',24,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(345,'Z',24,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(346,'1',25,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(347,'2',25,'Property Damage Liability','Liability');
insert into pa_coverage_code values(348,'3',25,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(349,'4',25,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(350,'5',25,'Medical Payments','Liability');
insert into pa_coverage_code values(351,'6',25,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(352,'7',25,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(353,'8',25,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(354,'9',25,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(355,'X',25,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(356,'Y',25,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(357,'T',25,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(358,'H',25,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(359,'W',25,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(360,'Z',25,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(361,'1',26,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(362,'2',26,'Property Damage Liability','Liability');
insert into pa_coverage_code values(363,'3',26,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(364,'4',26,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(365,'5',26,'Medical Payments','Liability');
insert into pa_coverage_code values(366,'6',26,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(367,'7',26,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(368,'8',26,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(369,'9',26,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(370,'X',26,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(371,'Y',26,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(372,'T',26,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(373,'H',26,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(374,'W',26,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(375,'Z',26,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(376,'1',27,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(377,'2',27,'Property Damage Liability','Liability');
insert into pa_coverage_code values(378,'3',27,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(379,'4',27,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(380,'5',27,'Medical Payments','Liability');
insert into pa_coverage_code values(381,'6',27,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(382,'7',27,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(383,'8',27,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(384,'9',27,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(385,'X',27,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(386,'Y',27,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(387,'T',27,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(388,'H',27,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(389,'W',27,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(390,'Z',27,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(391,'1',28,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(392,'2',28,'Property Damage Liability','Liability');
insert into pa_coverage_code values(393,'3',28,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(394,'4',28,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(395,'5',28,'Medical Payments','Liability');
insert into pa_coverage_code values(396,'6',28,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(397,'7',28,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(398,'8',28,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(399,'9',28,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(400,'X',28,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(401,'Y',28,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(402,'T',28,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(403,'H',28,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(404,'W',28,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(405,'Z',28,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(406,'1',29,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(407,'2',29,'Property Damage Liability','Liability');
insert into pa_coverage_code values(408,'3',29,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(409,'4',29,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(410,'5',29,'Medical Payments','Liability');
insert into pa_coverage_code values(411,'6',29,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(412,'7',29,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(413,'8',29,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(414,'9',29,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(415,'X',29,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(416,'Y',29,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(417,'T',29,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(418,'H',29,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(419,'W',29,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(420,'Z',29,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(421,'1',30,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(422,'2',30,'Property Damage Liability','Liability');
insert into pa_coverage_code values(423,'3',30,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(424,'4',30,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(425,'5',30,'Medical Payments','Liability');
insert into pa_coverage_code values(426,'6',30,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(427,'7',30,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(428,'8',30,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(429,'9',30,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(430,'X',30,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(431,'Y',30,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(432,'T',30,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(433,'H',30,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(434,'W',30,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(435,'Z',30,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(436,'1',31,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(437,'2',31,'Property Damage Liability','Liability');
insert into pa_coverage_code values(438,'3',31,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(439,'4',31,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(440,'5',31,'Medical Payments','Liability');
insert into pa_coverage_code values(441,'6',31,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(442,'7',31,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(443,'8',31,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(444,'9',31,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(445,'X',31,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(446,'Y',31,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(447,'T',31,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(448,'H',31,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(449,'W',31,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(450,'Z',31,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(451,'1',32,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(452,'2',32,'Property Damage Liability','Liability');
insert into pa_coverage_code values(453,'3',32,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(454,'4',32,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(455,'5',32,'Medical Payments','Liability');
insert into pa_coverage_code values(456,'6',32,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(457,'7',32,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(458,'8',32,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(459,'9',32,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(460,'X',32,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(461,'Y',32,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(462,'T',32,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(463,'H',32,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(464,'W',32,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(465,'Z',32,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(466,'1',33,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(467,'2',33,'Property Damage Liability','Liability');
insert into pa_coverage_code values(468,'3',33,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(469,'4',33,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(470,'5',33,'Medical Payments','Liability');
insert into pa_coverage_code values(471,'6',33,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(472,'7',33,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(473,'8',33,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(474,'9',33,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(475,'X',33,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(476,'Y',33,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(477,'T',33,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(478,'H',33,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(479,'W',33,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(480,'Z',33,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(481,'1',34,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(482,'2',34,'Property Damage Liability','Liability');
insert into pa_coverage_code values(483,'3',34,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(484,'4',34,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(485,'5',34,'Medical Payments','Liability');
insert into pa_coverage_code values(486,'6',34,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(487,'7',34,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(488,'8',34,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(489,'9',34,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(490,'X',34,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(491,'Y',34,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(492,'T',34,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(493,'H',34,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(494,'W',34,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(495,'Z',34,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(496,'1',35,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(497,'2',35,'Property Damage Liability','Liability');
insert into pa_coverage_code values(498,'3',35,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(499,'4',35,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(500,'5',35,'Medical Payments','Liability');
insert into pa_coverage_code values(501,'6',35,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(502,'7',35,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(503,'8',35,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(504,'9',35,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(505,'X',35,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(506,'Y',35,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(507,'T',35,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(508,'H',35,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(509,'W',35,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(510,'Z',35,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(511,'1',36,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(512,'2',36,'Property Damage Liability','Liability');
insert into pa_coverage_code values(513,'3',36,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(514,'4',36,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(515,'5',36,'Medical Payments','Liability');
insert into pa_coverage_code values(516,'6',36,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(517,'7',36,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(518,'8',36,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(519,'9',36,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(520,'X',36,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(521,'Y',36,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(522,'T',36,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(523,'H',36,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(524,'W',36,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(525,'Z',36,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(526,'1',38,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(527,'2',38,'Property Damage Liability','Liability');
insert into pa_coverage_code values(528,'3',38,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(529,'4',38,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(530,'5',38,'Medical Payments','Liability');
insert into pa_coverage_code values(531,'6',38,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(532,'7',38,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(533,'8',38,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(534,'9',38,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(535,'X',38,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(536,'Y',38,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(537,'T',38,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(538,'H',38,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(539,'W',38,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(540,'Z',38,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(541,'1',39,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(542,'2',39,'Property Damage Liability','Liability');
insert into pa_coverage_code values(543,'3',39,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(544,'4',39,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(545,'5',39,'Medical Payments','Liability');
insert into pa_coverage_code values(546,'6',39,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(547,'7',39,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(548,'8',39,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(549,'9',39,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(550,'X',39,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(551,'Y',39,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(552,'T',39,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(553,'H',39,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(554,'W',39,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(555,'Z',39,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(556,'1',40,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(557,'2',40,'Property Damage Liability','Liability');
insert into pa_coverage_code values(558,'3',40,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(559,'4',40,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(560,'5',40,'Medical Payments','Liability');
insert into pa_coverage_code values(561,'6',40,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(562,'7',40,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(563,'8',40,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(564,'9',40,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(565,'X',40,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(566,'Y',40,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(567,'T',40,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(568,'H',40,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(569,'W',40,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(570,'Z',40,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(571,'1',41,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(572,'2',41,'Property Damage Liability','Liability');
insert into pa_coverage_code values(573,'3',41,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(574,'4',41,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(575,'5',41,'Medical Payments','Liability');
insert into pa_coverage_code values(576,'6',41,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(577,'7',41,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(578,'8',41,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(579,'9',41,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(580,'X',41,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(581,'Y',41,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(582,'T',41,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(583,'H',41,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(584,'W',41,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(585,'Z',41,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(586,'1',42,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(587,'2',42,'Property Damage Liability','Liability');
insert into pa_coverage_code values(588,'3',42,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(589,'4',42,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(590,'5',42,'Medical Payments','Liability');
insert into pa_coverage_code values(591,'6',42,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(592,'7',42,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(593,'8',42,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(594,'9',42,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(595,'X',42,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(596,'Y',42,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(597,'T',42,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(598,'H',42,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(599,'W',42,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(600,'Z',42,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(601,'1',43,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(602,'2',43,'Property Damage Liability','Liability');
insert into pa_coverage_code values(603,'3',43,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(604,'4',43,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(605,'5',43,'Medical Payments','Liability');
insert into pa_coverage_code values(606,'6',43,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(607,'7',43,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(608,'8',43,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(609,'9',43,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(610,'X',43,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(611,'Y',43,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(612,'T',43,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(613,'H',43,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(614,'W',43,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(615,'Z',43,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(616,'1',44,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(617,'2',44,'Property Damage Liability','Liability');
insert into pa_coverage_code values(618,'3',44,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(619,'4',44,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(620,'5',44,'Medical Payments','Liability');
insert into pa_coverage_code values(621,'6',44,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(622,'7',44,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(623,'8',44,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(624,'9',44,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(625,'X',44,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(626,'Y',44,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(627,'T',44,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(628,'H',44,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(629,'W',44,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(630,'Z',44,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(631,'1',45,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(632,'2',45,'Property Damage Liability','Liability');
insert into pa_coverage_code values(633,'3',45,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(634,'4',45,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(635,'5',45,'Medical Payments','Liability');
insert into pa_coverage_code values(636,'6',45,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(637,'7',45,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(638,'8',45,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(639,'9',45,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(640,'X',45,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(641,'Y',45,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(642,'T',45,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(643,'H',45,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(644,'W',45,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(645,'Z',45,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(646,'1',46,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(647,'2',46,'Property Damage Liability','Liability');
insert into pa_coverage_code values(648,'3',46,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(649,'4',46,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(650,'5',46,'Medical Payments','Liability');
insert into pa_coverage_code values(651,'6',46,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(652,'7',46,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(653,'8',46,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(654,'9',46,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(655,'X',46,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(656,'Y',46,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(657,'T',46,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(658,'H',46,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(659,'W',46,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(660,'Z',46,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(661,'1',47,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(662,'2',47,'Property Damage Liability','Liability');
insert into pa_coverage_code values(663,'3',47,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(664,'4',47,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(665,'5',47,'Medical Payments','Liability');
insert into pa_coverage_code values(666,'6',47,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(667,'7',47,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(668,'8',47,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(669,'9',47,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(670,'X',47,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(671,'Y',47,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(672,'T',47,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(673,'H',47,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(674,'W',47,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(675,'Z',47,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(676,'1',48,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(677,'2',48,'Property Damage Liability','Liability');
insert into pa_coverage_code values(678,'3',48,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(679,'4',48,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(680,'5',48,'Medical Payments','Liability');
insert into pa_coverage_code values(681,'6',48,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(682,'7',48,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(683,'8',48,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(684,'9',48,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(685,'X',48,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(686,'Y',48,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(687,'T',48,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(688,'H',48,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(689,'W',48,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(690,'Z',48,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(691,'1',49,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(692,'2',49,'Property Damage Liability','Liability');
insert into pa_coverage_code values(693,'3',49,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(694,'4',49,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(695,'5',49,'Medical Payments','Liability');
insert into pa_coverage_code values(696,'6',49,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(697,'7',49,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(698,'8',49,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(699,'9',49,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(700,'X',49,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(701,'Y',49,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(702,'T',49,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(703,'H',49,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(704,'W',49,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(705,'Z',49,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(706,'1',50,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(707,'2',50,'Property Damage Liability','Liability');
insert into pa_coverage_code values(708,'3',50,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(709,'4',50,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(710,'5',50,'Medical Payments','Liability');
insert into pa_coverage_code values(711,'6',50,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(712,'7',50,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(713,'8',50,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(714,'9',50,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(715,'X',50,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(716,'Y',50,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(717,'T',50,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(718,'H',50,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(719,'W',50,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(720,'Z',50,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(721,'1',51,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(722,'2',51,'Property Damage Liability','Liability');
insert into pa_coverage_code values(723,'3',51,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(724,'4',51,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(725,'5',51,'Medical Payments','Liability');
insert into pa_coverage_code values(726,'6',51,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(727,'7',51,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(728,'8',51,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(729,'9',51,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(730,'X',51,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(731,'Y',51,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(732,'T',51,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(733,'H',51,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(734,'W',51,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(735,'Z',51,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(736,'1',52,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(737,'2',52,'Property Damage Liability','Liability');
insert into pa_coverage_code values(738,'3',52,'Bodily Injury and Property Damage Liability - Indivisible Premium','Liability');
insert into pa_coverage_code values(739,'4',52,'Personal Injury Protection','Liability');
insert into pa_coverage_code values(740,'5',52,'Medical Payments','Liability');
insert into pa_coverage_code values(741,'6',52,'Uninsured/Underinsured Motorists - Indivisible Premium','Liability');
insert into pa_coverage_code values(742,'7',52,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(743,'8',52,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(744,'9',52,'All Other Property and Liability Coverages','All Other');
insert into pa_coverage_code values(745,'X',52,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(746,'Y',52,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(747,'T',52,'Physical Damage - Other Than Collision - Additional Coverage Records','Physical Damage');
insert into pa_coverage_code values(748,'H',52,'Certified acts of terrorism covered (coverage not excluded) -- liability only','Terrorism Coverages');
insert into pa_coverage_code values(749,'W',52,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages');
insert into pa_coverage_code values(750,'Z',52,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages');
insert into pa_coverage_code values(751,'1',3,'Bodily Injury Liability','Liability');
insert into pa_coverage_code values(752,'2',3,'Property Damage Liability','Liability');
insert into pa_coverage_code values(753,'3',3,'Bodily Injury and Property Damage Liability Combined','Liability');
insert into pa_coverage_code values(754,'5',3,'Medical Payments','Liability');
insert into pa_coverage_code values(755,'6',3,'Uninsured/Underinsured Motorists Indivisible Premium','Liability');
insert into pa_coverage_code values(756,'7',3,'Physical Damage - Collision','Physical Damage');
insert into pa_coverage_code values(757,'8',3,'Physical Damage - Other Than Collision','Physical Damage');
insert into pa_coverage_code values(758,'9',3,'All Other','All Other');
insert into pa_coverage_code values(759,'X',3,'Uninsured Motorist','Liability');
insert into pa_coverage_code values(760,'Y',3,'Underinsured Motorist','Liability');
insert into pa_coverage_code values(761,'S',3,'Medical Benefits','Medical Benefits');
insert into pa_coverage_code values(762,'U',3,'Loss of Income','Loss of Income');
insert into pa_coverage_code values(763,'V',3,'Accidental Death','Accidental Death');
insert into pa_coverage_code values(764,'W',3,'Certified acts of terrorism covered (coverage not excluded) -- physical damage only','Terrorism Coverages ');
insert into pa_coverage_code values(765,'Z',3,'Certified acts of terrorism covered (coverage not excluded) -- liability and physical damage','Terrorism Coverages ');
