#
# SPDX-License-Identifier: Apache-2.0
#
global:
  clusterurl: aais.test.io
  appsecret: apps-secret
  hdssecret: hds-secret
  hdsconfigmap: hds-configmap
  datacallapp:
    install: true
    port: 8080
    targetport: 8080
    nodeport: 30000
    servicename: data-call-app-service
    ingresshostname: data-call-app-aais.test.io
  ui:
    install: true
    servicename: ui-service
    port: 8080
    targetport: 8080
  etl:
    install: false
    port: 8081
    targetport: 8081
    servicename: nifi-service
    httpservicename: nifi-http-service
    zkcsservicename: zk-cs-service
    zkhsservicename: zk-hs-service
  insurancedatamanager:
    install: true
    port: 8080
    targetport: 8080
    servicename: insurance-data-manager-service
  datacallprocessor:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-processor-service
  mongodb:
    install: true
    servicename: mongodb-service
  mongoexpress:
    install: true
    servicename: mongo-express-service
  upload:
    install: true
    port: 80
    targetport: 80
    servicename: upload-service