
DO $$ 
BEGIN
CREATE TABLE IF NOT EXISTS im_class_code (
    id INT,
    code VARCHAR,
    name VARCHAR,
    type VARCHAR,
    effective_date DATE NOT NULL DEFAULT '1900-01-01',
    expiration_date DATE NOT NULL DEFAULT '9999-12-31'
);

IF NOT EXISTS (SELECT * FROM im_class_code) THEN 
    INSERT INTO im_class_code VALUES(1,'100','Womens Wear, All risk','Garment Contractors');
    INSERT INTO im_class_code VALUES(2,'101','Womens Wear, All risk including premises','Garment Contractors');
    INSERT INTO im_class_code VALUES(3,'102','Womens Wear, All property','Garment Contractors');
    INSERT INTO im_class_code VALUES(4,'103','Mens Wear, Named perils','Garment Contractors');
    INSERT INTO im_class_code VALUES(5,'104','Mens Wear, Named perils and premises','Garment Contractors');
    INSERT INTO im_class_code VALUES(6,'105','Mens Wear, All risk','Garment Contractors');
    INSERT INTO im_class_code VALUES(7,'106','Mens Wear, All risk including premises','Garment Contractors');
    INSERT INTO im_class_code VALUES(8,'107','Mens Wear, All property','Garment Contractors');
    INSERT INTO im_class_code VALUES(9,'108','Others, Named perils','Garment Contractors');
    INSERT INTO im_class_code VALUES(10,'109','Others, Named perils and premises','Garment Contractors');
    INSERT INTO im_class_code VALUES(11,'110','Others, All risk','Garment Contractors');
    INSERT INTO im_class_code VALUES(12,'111','Others, All risk including premises','Garment Contractors');
    INSERT INTO im_class_code VALUES(13,'112','Others, All property','Garment Contractors');
    INSERT INTO im_class_code VALUES(14,'113','With gemprint credit','Jewelry Floater');
    INSERT INTO im_class_code VALUES(15,'114','All other classes','Golfers Equipment Floater');
    INSERT INTO im_class_code VALUES(16,'115','All classes','Government Service');
    INSERT INTO im_class_code VALUES(17,'116','All classes','Gun Floater');
    INSERT INTO im_class_code VALUES(18,'117','All classes','Grain Floater');
    INSERT INTO im_class_code VALUES(19,'118','Retailers, Non-reporting','Heating & Air Conditioning Dealers');
    INSERT INTO im_class_code VALUES(20,'119','Retailers, Reporting','Heating & Air Conditioning Dealers');
    INSERT INTO im_class_code VALUES(21,'120','Wholesalers and distributors','Heating & Air Conditioning Dealers');
    INSERT INTO im_class_code VALUES(22,'121','Horse and Wagon','All classes');
    INSERT INTO im_class_code VALUES(23,'122','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(24,'123','Farm Equipment, Non-reporting, No incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(25,'124','Farm Equipment, Reporting, No incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(26,'125','Farm Equipment, Non-reporting, With incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(27,'126','Farm Equipment, Reporting, With incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(28,'127','Construction Equip, Non-reporting, No incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(29,'128','Construction Equip, Reporting, No incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(30,'129','Construction Equip, Non-reporting, With incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(31,'130','Construction Equip, Reporting, With incidental stock','Implement Dealers Stock Floater');
    INSERT INTO im_class_code VALUES(32,'131','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(33,'132','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(34,'133','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(35,'134','All classes','Installation Risks');
    INSERT INTO im_class_code VALUES(36,'135','All classes','Installation or Building Materials - Job Site');
    INSERT INTO im_class_code VALUES(37,'136','Residential, Single job','Builders Risk');
    INSERT INTO im_class_code VALUES(38,'137','Residential, Blanket','Builders Risk');
    INSERT INTO im_class_code VALUES(39,'138','Residential, Excess of loss','Builders Risk');
    INSERT INTO im_class_code VALUES(40,'139','Mercantile, Single job','Builders Risk');
    INSERT INTO im_class_code VALUES(41,'140','Mercantile, Blanket','Builders Risk');
    INSERT INTO im_class_code VALUES(42,'141','Mercantile, Excess of loss','Builders Risk');
    INSERT INTO im_class_code VALUES(43,'142','All Others, Single job','Builders Risk');
    INSERT INTO im_class_code VALUES(44,'143','All Others, Blanket','Builders Risk');
    INSERT INTO im_class_code VALUES(45,'144','All Others, Excess of loss','Builders Risk');
    INSERT INTO im_class_code VALUES(46,'145','Standard, Loose Diamond Dealers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(47,'146','Standard, Loose Diamond Dealers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(48,'147','Standard, Jewelry Wholesalers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(49,'148','Standard, Jewelry Wholesalers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(50,'149','Standard, Jewelry Retailers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(51,'150','Standard, Jewelry Retailers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(52,'151','Standard, Pawnbrokers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(53,'152','Standard, Pawnbrokers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(54,'153','Standard, Jewelry Manufacturers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(55,'154','Standard, Jewelry Manufacturers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(56,'155','Restricted, Loose Diamond Dealers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(57,'156','Restricted, Loose Diamond Dealers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(58,'157','Restricted, Jewelry Wholesalers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(59,'158','Restricted, Jewelry Wholesalers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(60,'159','Restricted, Jewelry Retailers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(61,'160','Restricted, Jewelry Retailers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(62,'161','Restricted, Pawnbrokers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(63,'162','Restricted, Pawnbrokers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(64,'163','Restricted, Jewelry Manufacturers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(65,'164','Restricted, Jewelry Manufacturers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(66,'165','All other classes','Leased Property');
    INSERT INTO im_class_code VALUES(67,'166','All classes','Linen & Uniform Supply Floater');
    INSERT INTO im_class_code VALUES(68,'167','All classes','Live Animals and Pelts');
    INSERT INTO im_class_code VALUES(69,'168','Blanket, No optional perils','Livestock Floater');
    INSERT INTO im_class_code VALUES(70,'169','Scheduled, No optional perils','Livestock Floater');
    INSERT INTO im_class_code VALUES(71,'170','Feedlot and Miscellaneous Livestock','Livestock Floater');
    INSERT INTO im_class_code VALUES(72,'171','Blanket, All optional perils','Livestock Floater');
    INSERT INTO im_class_code VALUES(73,'172','Scheduled, All optional perils','Livestock Floater');
    INSERT INTO im_class_code VALUES(74,'173','Scheduled, Optional Perils, No sheep','Livestock Floater');
    INSERT INTO im_class_code VALUES(75,'174','Blanket, Optional Perils, No sheep','Livestock Floater');
    INSERT INTO im_class_code VALUES(76,'175','All classes','Logging Equipment');
    INSERT INTO im_class_code VALUES(77,'176','Business machinery','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(78,'177','Coin operated device - amusement','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(79,'178','Golf carts','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(80,'179','Vending machines','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(81,'180','Voting machines','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(82,'181','Parking meters','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(83,'182','All others','Machinery and Mechanical Equipment');
    INSERT INTO im_class_code VALUES(84,'183','All classes','School Property Floater');
    INSERT INTO im_class_code VALUES(85,'184','All classes','Municipal Property Floater');
    INSERT INTO im_class_code VALUES(86,'185','All classes','Audio Visual Equipment');
    INSERT INTO im_class_code VALUES(87,'186','All classes','Hospital Property Floater');
    INSERT INTO im_class_code VALUES(88,'187','Retailers, Non-reporting','Marine Supply and Boat Dealers');
    INSERT INTO im_class_code VALUES(89,'188','Retailers, Reporting','Marine Supply and Boat Dealers');
    INSERT INTO im_class_code VALUES(90,'189','Wholesalers and distributors','Marine Supply and Boat Dealers');
    INSERT INTO im_class_code VALUES(91,'190','Marine operator legal liability','Marine Supply and Boat Dealers');
    INSERT INTO im_class_code VALUES(92,'191','All classes','Merchandise Floater');
    INSERT INTO im_class_code VALUES(93,'192','Personal','All Other Classes Not Specified');
    INSERT INTO im_class_code VALUES(94,'193','Commercial','All Other Classes Not Specified');
    INSERT INTO im_class_code VALUES(95,'194','Reporting policies','Merchants Property');
    INSERT INTO im_class_code VALUES(96,'195','Non-reporting policies','Merchants Property');
    INSERT INTO im_class_code VALUES(97,'196','Strip Mining','Mine Equipment and Rolling Stock');
    INSERT INTO im_class_code VALUES(98,'197','Underground Mining','Mine Equipment and Rolling Stock');
    INSERT INTO im_class_code VALUES(99,'198','Reporting policies','Mobile Home Dealers including Trailers');
    INSERT INTO im_class_code VALUES(100,'199','Non-reporting policies','Mobile Home Dealers including Trailers');
    INSERT INTO im_class_code VALUES(101,'200','Equipment','Morticians');
    INSERT INTO im_class_code VALUES(102,'201','Liability','Morticians');
    INSERT INTO im_class_code VALUES(103,'202','Owners Form, Under 100 miles','Motor Truck Cargo');
    INSERT INTO im_class_code VALUES(104,'203','Owners Form, Over 100 miles','Motor Truck Cargo');
    INSERT INTO im_class_code VALUES(105,'204','Carriers Form, Under 100 miles','Motor Truck Cargo');
    INSERT INTO im_class_code VALUES(106,'205','Carriers Form, Over 100 miles','Motor Truck Cargo');
    INSERT INTO im_class_code VALUES(107,'206','Carriers Form, Retrospective','Motor Truck Cargo');
    INSERT INTO im_class_code VALUES(108,'207','Individual, Non professional','Musical Instruments');
    INSERT INTO im_class_code VALUES(109,'208','Individual, Professional','Musical Instruments');
    INSERT INTO im_class_code VALUES(110,'209','Dance Bands and orchestras','Musical Instruments');
    INSERT INTO im_class_code VALUES(111,'210','Other orchestras, bands, etc.','Musical Instruments');
    INSERT INTO im_class_code VALUES(112,'211','Stationary organs','Musical Instruments');
    INSERT INTO im_class_code VALUES(113,'212','Non-reporting','Musical Instrument Dealers');
    INSERT INTO im_class_code VALUES(114,'213','Reporting','Musical Instrument Dealers');
    INSERT INTO im_class_code VALUES(115,'214','All classes','Signs and Clocks');
    INSERT INTO im_class_code VALUES(116,'215','Retailers, Excluding reporting form','Office Machines and Supply Dealers');
    INSERT INTO im_class_code VALUES(117,'216','Retailers, Reporting form','Office Machines and Supply Dealers');
    INSERT INTO im_class_code VALUES(118,'217','Wholesalers and distributors','Office Machines and Supply Dealers');
    INSERT INTO im_class_code VALUES(119,'218','Cable tools and other equipment','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(120,'219','Well servicing equipment','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(121,'220','Coastal rotary','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(122,'221','Inland Rotary','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(123,'222','All classes','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(124,'223','Coastal territory','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(125,'224','Inland territory','Oil and Gas Drilling Rigs');
    INSERT INTO im_class_code VALUES(126,'225','Open form','Parcel Post');
    INSERT INTO im_class_code VALUES(127,'226','Personal','Paraphernalia');
    INSERT INTO im_class_code VALUES(128,'227','Commercial','Paraphernalia');
    INSERT INTO im_class_code VALUES(129,'228','Legal liability only','Pattern Floater');
    INSERT INTO im_class_code VALUES(130,'229','All others','Pattern Floater');
    INSERT INTO im_class_code VALUES(131,'230','Trailer contents (auto home)','Personal Effects');
    INSERT INTO im_class_code VALUES(132,'231','Travel (ticket) baggage','Personal Effects');
    INSERT INTO im_class_code VALUES(133,'232','All other','Personal Effects');
    INSERT INTO im_class_code VALUES(134,'233','All classes','Fur Floater');
    INSERT INTO im_class_code VALUES(135,'234','Without gemprint credit','Jewelry Floater');
    INSERT INTO im_class_code VALUES(136,'235','Blanket portion','Personal Property Floater');
    INSERT INTO im_class_code VALUES(137,'236','Outdoor radio and TV towers and antennas','Personal Property Floater');
    INSERT INTO im_class_code VALUES(138,'237','Miscellaneous scheduled property','Personal Property Floater');
    INSERT INTO im_class_code VALUES(139,'238','With extended coverage','Physicians and Surgeons Equipment');
    INSERT INTO im_class_code VALUES(140,'239','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(141,'240','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(142,'241','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(143,'242','Without extended coverage','Physicians and Surgeons');
    INSERT INTO im_class_code VALUES(144,'243','All classes','Poultry Floater');
    INSERT INTO im_class_code VALUES(145,'244','Insureds property on other premises','Processing Risks');
    INSERT INTO im_class_code VALUES(146,'245','Customers property on insureds premises','Processing Risks');
    INSERT INTO im_class_code VALUES(147,'246','Retailers, Non-reporting forms','Professional or Scientific Instruments Dealers');
    INSERT INTO im_class_code VALUES(148,'247','Retailers, Reporting forms','Professional or Scientific Instruments Dealers');
    INSERT INTO im_class_code VALUES(149,'248','Wholesalers and distributors','Professional or Scientific Instruments Dealers');
    INSERT INTO im_class_code VALUES(150,'249','All classes','Radioactive Contamination Coverage');
    INSERT INTO im_class_code VALUES(151,'250','All classes','Radio and TV Dealers & Repairers');
    INSERT INTO im_class_code VALUES(152,'251','Commercial, Towers and Antennas, Property damage','Radio and TV');
    INSERT INTO im_class_code VALUES(153,'252','Commercial, Towers and Antennas, Use and occupancy','Radio and TV');
    INSERT INTO im_class_code VALUES(154,'253','Commercial, Broadcasting Equipment, Property damage','Radio and TV');
    INSERT INTO im_class_code VALUES(155,'254','Commercial, Broadcasting Equipment, Use and occupancy','Radio and TV');
    INSERT INTO im_class_code VALUES(156,'255','Commercial, Towers and Antennas Builders risk','Radio and TV');
    INSERT INTO im_class_code VALUES(157,'256','Commercial, Cable TV, Property damage','Radio and TV');
    INSERT INTO im_class_code VALUES(158,'257','Commercial, Cable TV, Use and occupancy','Radio and TV');
    INSERT INTO im_class_code VALUES(159,'258','All classes','Radium Floater');
    INSERT INTO im_class_code VALUES(160,'259','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(161,'260','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(162,'261','Short haul','Railroad Risks');
    INSERT INTO im_class_code VALUES(163,'262','Yard switching','Railroad Risks');
    INSERT INTO im_class_code VALUES(164,'263','Equipment excluding locomotives','Railroad Risks');
    INSERT INTO im_class_code VALUES(165,'264','Tank cars','Railroad Risks');
    INSERT INTO im_class_code VALUES(166,'265','Miscellaneous','Railroad Risks');
    INSERT INTO im_class_code VALUES(167,'266','PD Portion','Recreational Vehicles');
    INSERT INTO im_class_code VALUES(168,'267','P & I Portion','Recreational Vehicles');
    INSERT INTO im_class_code VALUES(169,'268','All classes','Registered Mail');
    INSERT INTO im_class_code VALUES(170,'269','Direct Coverage, Owners interest','Rigging');
    INSERT INTO im_class_code VALUES(171,'270','Direct Coverage, Riggers interest','Rigging');
    INSERT INTO im_class_code VALUES(172,'271','Legal liability imposed by law','Rigging');
    INSERT INTO im_class_code VALUES(173,'272','All classes','Saddles and Bridles');
    INSERT INTO im_class_code VALUES(174,'273','Wearing apparel','Salespersons Samples');
    INSERT INTO im_class_code VALUES(175,'274','All others','Salespersons Samples');
    INSERT INTO im_class_code VALUES(176,'275','All classes','Scientific Instruments');
    INSERT INTO im_class_code VALUES(177,'276','All classes','Sidetrack Liability');
    INSERT INTO im_class_code VALUES(178,'277','All classes','Silverware Floater');
    INSERT INTO im_class_code VALUES(179,'278','PD Portion','Snowmobiles');
    INSERT INTO im_class_code VALUES(180,'279','P & I Portion','Snowmobiles');
    INSERT INTO im_class_code VALUES(181,'280','All classes','Sports Equipment');
    INSERT INTO im_class_code VALUES(182,'281','Retailers, Non-reporting forms','Sporting Goods Dealers');
    INSERT INTO im_class_code VALUES(183,'282','Retailers, Reporting forms','Sporting Goods Dealers');
    INSERT INTO im_class_code VALUES(184,'283','Wholesalers and distributors','Sporting Goods Dealers');
    INSERT INTO im_class_code VALUES(185,'284','Private','Stamp Collections');
    INSERT INTO im_class_code VALUES(186,'285','Dealers','Stamp Collections');
    INSERT INTO im_class_code VALUES(187,'286','Others','Stamp Collections');
    INSERT INTO im_class_code VALUES(188,'287','All classes','Tobacco Curing System');
    INSERT INTO im_class_code VALUES(189,'288','All classes','Tanks');
    INSERT INTO im_class_code VALUES(190,'289','All classes','Tank Contents');
    INSERT INTO im_class_code VALUES(191,'290','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(192,'291','All classes','Theatrical Floaters');
    INSERT INTO im_class_code VALUES(193,'292','All classes','Tourists Baggage');
    INSERT INTO im_class_code VALUES(194,'293','All classes','Tools and Equipment Floater');
    INSERT INTO im_class_code VALUES(195,'294','Personal','Trailer Contents');
    INSERT INTO im_class_code VALUES(196,'295','Camping and mobile home','Trailers');
    INSERT INTO im_class_code VALUES(197,'296','All other','Trailers');
    INSERT INTO im_class_code VALUES(198,'297','Pipe Lines, Property damage','Transmission and Pipe Lines');
    INSERT INTO im_class_code VALUES(199,'298','Pipe Lines, Use and occupancy','Transmission and Pipe Lines');
    INSERT INTO im_class_code VALUES(200,'299','Non Commercial, House and Pontoon, Over 26 ft, No motor','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(201,'300','Power, Telegraph, phone, Property damage','Transmission and Pipe Lines');
    INSERT INTO im_class_code VALUES(202,'301','Power, Telegraph, phone, Use and occupancy','Transmission and Pipe Lines');
    INSERT INTO im_class_code VALUES(203,'302','Non-reporting','Commercial Property Policy');
    INSERT INTO im_class_code VALUES(204,'303','Reporting','Commercial Property Policy');
    INSERT INTO im_class_code VALUES(205,'304','Open and annual','Transportation Floater');
    INSERT INTO im_class_code VALUES(206,'305','Issued with garment contractors floater','Transportation Floater');
    INSERT INTO im_class_code VALUES(207,'306','Trip Transit, Household Goods, Owners','Transportation Floater');
    INSERT INTO im_class_code VALUES(208,'307','Trip Transit, Other Than Household Goods, Owners','Transportation Floater');
    INSERT INTO im_class_code VALUES(209,'308','Trip Transit, All others','Transportation Floater');
    INSERT INTO im_class_code VALUES(210,'309','Trip Transit, Household Goods, Public carrier','Transportation Floater');
    INSERT INTO im_class_code VALUES(211,'310','Trip Transit, Other Than Household Goods, Public carrier','Transportation Floater');
    INSERT INTO im_class_code VALUES(212,'311','All other classes','Use and Occupancy');
    INSERT INTO im_class_code VALUES(213,'312','All other classes','Valuable Papers and Records');
    INSERT INTO im_class_code VALUES(214,'313','All other classes','Veterinarians Bailee');
    INSERT INTO im_class_code VALUES(215,'314','All other classes','Warehousemens Legal Liability');
    INSERT INTO im_class_code VALUES(216,'315','All other classes','Wedding Presents');
    INSERT INTO im_class_code VALUES(217,'316','All other classes','Well Drilling Equipment');
    INSERT INTO im_class_code VALUES(218,'317','All other classes','Wool Growers Floater');
    INSERT INTO im_class_code VALUES(219,'318','Builders risk','Bridges and Tunnels');
    INSERT INTO im_class_code VALUES(220,'319','Property Damage, All risks','Bridges and Tunnels');
    INSERT INTO im_class_code VALUES(221,'320','Property Damage, Named perils','Bridges and Tunnels');
    INSERT INTO im_class_code VALUES(222,'321','Use and occupancy','Bridges and Tunnels');
    INSERT INTO im_class_code VALUES(223,'322','Private','Cameras and Sound Equipment');
    INSERT INTO im_class_code VALUES(224,'323','Motion picture producer','Cameras and Sound Equipment');
    INSERT INTO im_class_code VALUES(225,'324','Television','Cameras and Sound Equipment');
    INSERT INTO im_class_code VALUES(226,'325','Other commercial','Cameras and Sound Equipment');
    INSERT INTO im_class_code VALUES(227,'326','Reporting form','Camera Dealers');
    INSERT INTO im_class_code VALUES(228,'327','Non-reporting form','Camera Dealers');
    INSERT INTO im_class_code VALUES(229,'328','Non-reporting','Commercial Block');
    INSERT INTO im_class_code VALUES(230,'329','Reporting','Commercial Block');
    INSERT INTO im_class_code VALUES(231,'330','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(232,'331','Locomotives including equipment','Railroad Risks');
    INSERT INTO im_class_code VALUES(233,'332','Winter range livestock','Livestock Floater');
    INSERT INTO im_class_code VALUES(234,'333','Restricted, Watch Repairers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(235,'334','Restricted, Watch Repairers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(236,'335','Standard, Watch Repairers, Fire','Jewelers Block');
    INSERT INTO im_class_code VALUES(237,'336','Standard, Watch Repairers, All other perils','Jewelers Block');
    INSERT INTO im_class_code VALUES(238,'337','All classes','Hardware and Implement Dealers Floater');
    INSERT INTO im_class_code VALUES(239,'338','All classes','Dwelling Contents Floater');
    INSERT INTO im_class_code VALUES(240,'339','Non Commercial, Outboards and Canoes, Under 50 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(241,'340','All classes','Builders Risk and Installation Combined');
    INSERT INTO im_class_code VALUES(242,'341','All Classes, Commercial','Boats, P & I Portion');
    INSERT INTO im_class_code VALUES(243,'342','All Classes, Personal','Boats, P & I Portion');
    INSERT INTO im_class_code VALUES(244,'343','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(245,'344','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(246,'345','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(247,'346','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(248,'347','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(249,'348','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(250,'349','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(251,'350','Motorized, without Collision','Golf Carts');
    INSERT INTO im_class_code VALUES(252,'351','Motorized, with Collision','Golf Carts');
    INSERT INTO im_class_code VALUES(253,'352','Motorized, Optional Medical Payments Coverage','Golf Carts');
    INSERT INTO im_class_code VALUES(254,'353','Motorized, Optional Limited Property Damage Liability','Golf Carts');
    INSERT INTO im_class_code VALUES(255,'354','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(256,'355','Motorized, without Collision','Grounds Care Vehicles');
    INSERT INTO im_class_code VALUES(257,'356','Motorized, with Collision','Grounds Care Vehicles');
    INSERT INTO im_class_code VALUES(258,'357','Motorized, Optional Medical Payments Coverage','Grounds Care Vehicles');
    INSERT INTO im_class_code VALUES(259,'358','Motorized, Optional Limited Property Damage Liability','Grounds Care Vehicles');
    INSERT INTO im_class_code VALUES(260,'359','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(261,'360','Motorized, without Collision','Mobility Assistance Vehicles');
    INSERT INTO im_class_code VALUES(262,'361','Motorized, with Collision','Mobility Assistance Vehicles');
    INSERT INTO im_class_code VALUES(263,'362','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(264,'363','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(265,'364','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(266,'365','Motorized, without Collision','Snowmobiles');
    INSERT INTO im_class_code VALUES(267,'366','Motorized, with Collision','Snowmobiles');
    INSERT INTO im_class_code VALUES(268,'367','Motorized, Optional Medical Payments Coverage','Snowmobiles');
    INSERT INTO im_class_code VALUES(269,'368','Motorized, Optional Limited Property Damage Liability','Snowmobiles');
    INSERT INTO im_class_code VALUES(270,'369','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(271,'370','Non-Commercial, Not More than 16 feet, Principally Operated on Inland Waters Other Than the Great Lakes','Boats and Outboard Motors, PD Portion');
    INSERT INTO im_class_code VALUES(272,'371','Non-Commercial, Not More than 16 feet, Principally Operated on the Great Lakes and/or Coastal Waters','Boats and Outboard Motors, PD Portion');
    INSERT INTO im_class_code VALUES(273,'372','Non-Commercial, Not More than 16 feet, Optional Medical Payments Coverage','Boats and Outboard Motors');
    INSERT INTO im_class_code VALUES(274,'373','Non-Commercial, Not More than 16 feet, Optional Limited Property Damage Liability','Boats and Outboard Motors');
    INSERT INTO im_class_code VALUES(275,'374','With Collision','Grounds Care Trailers');
    INSERT INTO im_class_code VALUES(276,'375','Without Collision','Grounds Care Trailers');
    INSERT INTO im_class_code VALUES(277,'376','Grounds Care Equipment','Grounds Care Equipment');
    INSERT INTO im_class_code VALUES(278,'377','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(279,'378','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(280,'379','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(281,'380','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(282,'001','Reporting','Accounts Receivable');
    INSERT INTO im_class_code VALUES(283,'002','Non-reporting','Accounts Receivable');
    INSERT INTO im_class_code VALUES(284,'003','All classes','Antique Automobiles');
    INSERT INTO im_class_code VALUES(285,'004','All classes','Antique Dealers');
    INSERT INTO im_class_code VALUES(286,'005','All classes','Armored Car and Messenger');
    INSERT INTO im_class_code VALUES(287,'006','All classes','Aviation Floater');
    INSERT INTO im_class_code VALUES(288,'007','Retailers, Reporting','Household Appliance Dealers');
    INSERT INTO im_class_code VALUES(289,'008','Retailers, Non-reporting','Household Appliance Dealers');
    INSERT INTO im_class_code VALUES(290,'009','Wholesalers and distributors','Household Appliance Dealers');
    INSERT INTO im_class_code VALUES(291,'010','Air Freight','All classes');
    INSERT INTO im_class_code VALUES(292,'011','Dry cleaners','Bailees Customers');
    INSERT INTO im_class_code VALUES(293,'012','Laundries','Bailees Customers');
    INSERT INTO im_class_code VALUES(294,'013','Rugs and carpets','Bailees Customers');
    INSERT INTO im_class_code VALUES(295,'014','All others','Bailees Customers');
    INSERT INTO im_class_code VALUES(296,'015','Bicycle Floater','All classes');
    INSERT INTO im_class_code VALUES(297,'016','Railroad','Bills of Lading');
    INSERT INTO im_class_code VALUES(298,'017','Non Commercial, Outboards & Canoes, No motor','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(299,'018','Non Commercial, Outboards & Canoes, Und 16 ft, Restricted from Great Lakes and Coastal','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(300,'019','Non Commercial, Outboards & Canoes, Und 16 ft, Unrestricted','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(301,'020','Non Commercial, Outboards & Canoes, 50 to 100 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(302,'021','Non Commercial, Outboards & Canoes, Over 100 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(303,'022','Non Commercial, Sailboats, 26 ft & under, Motorized','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(304,'023','Non Commercial, Sailboats, 26 ft & under, No motor','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(305,'024','Non Commercial, Sailboats, Over 26 ft, Motorized','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(306,'025','Non Commercial, Sailboats, Over 26 ft, No motor','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(307,'026','Non Commercial, Inboard/Outboards, 26 ft & und, 150 hp & und','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(308,'027','Non Commercial, Inboard/Outboards, 26 ft & und, Over 150 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(309,'028','Non Commercial, Inboard/Outboards, Over 26 ft, 150 hp & und','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(310,'029','Non Commercial, Inboard/Outboards, Over 26 ft, Over 150 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(311,'030','Non Commercial, Inboards, 26 ft & under, 150 hp & und','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(312,'031','Non Commercial, Inboards, 26 ft & under, Over 150 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(313,'032','Non Commercial, Inboards, Over 26 ft, 150 hp & under','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(314,'033','Non Commercial, Inboards, Over 26 ft, Over 150 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(315,'034','Non Commercial, House & Pontoon, 26 ft & under, No motor','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(316,'035','Non Commercial, House & Pontoon, 26 ft & under, Over 150 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(317,'036','Non Commercial, House & Pontoon, Over 26 ft, 150 hp & und','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(318,'037','Non Commercial, House & Pontoon, Over 26 ft, Over 150 hp','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(319,'038','Commercial Use, All classes','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(320,'039','Non Commercial, Not Otherwise Classified, All other classes','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(321,'040','All Classes','CDP');
    INSERT INTO im_class_code VALUES(322,'041','All classes including mobile and base units, phones, etc.','Citizens Band Radios');
    INSERT INTO im_class_code VALUES(323,'042','Private','Coin Collections');
    INSERT INTO im_class_code VALUES(324,'043','Dealers','Coin Collections');
    INSERT INTO im_class_code VALUES(325,'044','Others','Coin Collections');
    INSERT INTO im_class_code VALUES(326,'045','All classes','Cold Storage Locker');
    INSERT INTO im_class_code VALUES(327,'046','All classes','Contact Lenses');
    INSERT INTO im_class_code VALUES(328,'047','All risk form','Contractors Equipment');
    INSERT INTO im_class_code VALUES(329,'048','Named peril form','Contractors Equipment');
    INSERT INTO im_class_code VALUES(330,'049','Extra expense','Contractors Equipment');
    INSERT INTO im_class_code VALUES(331,'050','All classes','Contractors Equipment and Installation Combined');
    INSERT INTO im_class_code VALUES(332,'051','Excluding ginners','Cotton Buyers Transit');
    INSERT INTO im_class_code VALUES(333,'052','Ginners','Cotton Buyers Transit');
    INSERT INTO im_class_code VALUES(334,'053','Equipment','Data Processing');
    INSERT INTO im_class_code VALUES(335,'054','Media','Data Processing');
    INSERT INTO im_class_code VALUES(336,'055','Extra expense','Data Processing');
    INSERT INTO im_class_code VALUES(337,'056','Business interruption','Data Processing');
    INSERT INTO im_class_code VALUES(338,'057','All other classes','Dealers');
    INSERT INTO im_class_code VALUES(339,'058','Dual interest','Deferred Payment Merchandise');
    INSERT INTO im_class_code VALUES(340,'059','Single interest','Deferred Payment Merchandise');
    INSERT INTO im_class_code VALUES(341,'060','Contingent interest','Deferred Payment Merchandise');
    INSERT INTO im_class_code VALUES(342,'061','Personal, All classes','Radio & TV');
    INSERT INTO im_class_code VALUES(343,'062','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(344,'063','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(345,'064','All classes','Difference in Conditions');
    INSERT INTO im_class_code VALUES(346,'065','All classes','Docks, Piers, and Wharves');
    INSERT INTO im_class_code VALUES(347,'066','Non-reporting, No incidental stock','Equipment Dealers');
    INSERT INTO im_class_code VALUES(348,'067','Non Commercial, House & Pontoon, 26 ft & und, 150 hp & und','Boats, PD Portion');
    INSERT INTO im_class_code VALUES(349,'068','Reporting, No incidental stock','Equipment Dealers');
    INSERT INTO im_class_code VALUES(350,'069','Non-reporting, With incidental stock','Equipment Dealers');
    INSERT INTO im_class_code VALUES(351,'070','Reporting, With incidental stock','Equipment Dealers');
    INSERT INTO im_class_code VALUES(352,'071','Owners form, Owners property','Exhibition Risks');
    INSERT INTO im_class_code VALUES(353,'072','Exhibitors form, Loaned property','Exhibition Risks');
    INSERT INTO im_class_code VALUES(354,'073','Blanket','Farm Equipment');
    INSERT INTO im_class_code VALUES(355,'074','Scheduled','Farm Equipment');
    INSERT INTO im_class_code VALUES(356,'075','Reserved','Reserved');
    INSERT INTO im_class_code VALUES(357,'076','Extra expense','Farm Equipment');
    INSERT INTO im_class_code VALUES(358,'077','Irrigation equipment','Farm Equipment');
    INSERT INTO im_class_code VALUES(359,'078','All classes','Films and Negatives');
    INSERT INTO im_class_code VALUES(360,'079','Including antiques','Fine Arts');
    INSERT INTO im_class_code VALUES(361,'080','Other commercial collections','Fine Arts');
    INSERT INTO im_class_code VALUES(362,'081','Private Collection, Excluding antiques','Fine Arts');
    INSERT INTO im_class_code VALUES(363,'082','Dealers','Fine Arts');
    INSERT INTO im_class_code VALUES(364,'083','Museums','Fine Arts');
    INSERT INTO im_class_code VALUES(365,'084','Stained glass windows','Fine Arts');
    INSERT INTO im_class_code VALUES(366,'085','Form A','First Class Mail');
    INSERT INTO im_class_code VALUES(367,'086','Form B','First Class Mail');
    INSERT INTO im_class_code VALUES(368,'087','Transfer agent mail policy','First Class Mail');
    INSERT INTO im_class_code VALUES(369,'088','Dual interest','Floor Plan Merchandise');
    INSERT INTO im_class_code VALUES(370,'089','Single interest','Floor Plan Merchandise');
    INSERT INTO im_class_code VALUES(371,'090','Contingent interest','Floor Plan Merchandise');
    INSERT INTO im_class_code VALUES(372,'091','Reporting','Furriers Block');
    INSERT INTO im_class_code VALUES(373,'092','Non-reporting','Furriers Block');
    INSERT INTO im_class_code VALUES(374,'093','Custody rider','Furriers Customers');
    INSERT INTO im_class_code VALUES(375,'094','Legal Liability, Retail','Furriers Customers');
    INSERT INTO im_class_code VALUES(376,'095','Legal Liability, Wholesale','Furriers Customers');
    INSERT INTO im_class_code VALUES(377,'096','All others including certificates','Furriers Customers');
    INSERT INTO im_class_code VALUES(378,'097','Optional annual premium non-reporting','Furriers Customers');
    INSERT INTO im_class_code VALUES(379,'098','Womens Wear, Named perils','Garment Contractors');
    INSERT INTO im_class_code VALUES(380,'099','Womens Wear, Named perils and premises','Garment Contractors');
END IF;
END $$;
