#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.global.datacallapp.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openidl-data-call-app.fullname" . }}
  labels:
    {{- include "openidl-data-call-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openidl-data-call-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openidl-data-call-app.selectorLabels" . | nindent 8 }}
    spec:
      # {{- with .Values.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      volumes:
      - name: apkey
        secret:
          secretName: {{ .Values.global.appsecret }}
      containers:
      - name: {{ .Chart.Name }}
        # for regular deployment
        # image: aais:1
        # for local development against minikube registry
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}      
        ports:
        - containerPort: {{ .Values.global.datacallapp.port }}
        volumeMounts:
        {{- range .Values.secrets }}
        - name: apkey
          mountPath: /server/config/{{ .file }}
          subPath: {{ .name }}
        {{- end }}
{{- end }}