# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-call-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-call-processor
  template:
    metadata:
      labels:
        app: data-call-processor
    spec:
      volumes:
      - name: apkey
        secret:
          secretName: appssecret
      containers:
      - name: data-call-processor
        image: openidl/data-call-processor
        # for local development against minikube registry
        imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: apkey
          mountPath: /server/config/local-certmanager-config.json
          subPath: certmanager
        - name: apkey
          mountPath: /server/config/local-mongo-config.json
          subPath: mongodb
        - name: apkey
          mountPath: /server/config/local-cloudant-config.json
          subPath: cloudantdb
        - name: apkey
          mountPath: /server/config/connection-profile.json
          subPath: connectionprofile
      # - name: apkey
        # mountPath: /server/config/DBConfig.json
        # default.json
        # email.json
        # listener-channel-config.json
        # mappings.json
        # metadata.json
        # s3-bucket-config.json
        # target-channel-config.json
        # unique-identifiers-config.json
---
apiVersion: v1
kind: Service
metadata:
  name: data-call-processor
  labels:
    app: data-call-processor
spec:
  #type: NodePort
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
    # the port that this service should serve on
    #- port: 8080
    #  targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: data-call-processor
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: data-call-processor-ingress
#   annotations:
#     kubernetes.io/ingress.class: "public-iks-k8s-nginx"
# spec:
#   tls:
#   - hosts:
#     - data-call-processor.${CLUSTER_NAME}.us-east.containers.appdomain.cloud
#     secretName: ${CLUSTER_NAME}
#   rules:
#   - host: data-call-processor.${CLUSTER_NAME}.us-east.containers.appdomain.cloud
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: data-call-processor
#           servicePort: 8080