DO $$ 
BEGIN
CREATE TABLE IF NOT EXISTS ca_anti_theft_device_discount_code (
    id INT,
    fk_state_id INT,
    code VARCHAR,
    description VARCHAR
);
IF NOT EXISTS (SELECT * FROM ca_anti_theft_device_discount_code) THEN

    INSERT INTO ca_anti_theft_device_discount_code VALUES(1,1,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(2,1,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(3,1,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(4,1,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(5,1,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(6,1,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(7,1,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(8,2,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(9,2,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(10,2,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(11,2,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(12,2,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(13,2,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(14,2,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(15,3,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(16,3,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(17,3,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(18,3,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(19,3,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(20,3,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(21,3,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(22,4,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(23,4,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(24,4,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(25,4,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(26,4,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(27,4,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(28,4,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(29,5,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(30,5,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(31,5,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(32,5,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(33,5,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(34,5,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(35,5,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(36,6,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(37,6,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(38,6,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(39,6,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(40,6,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(41,6,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(42,6,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(43,7,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(44,7,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(45,7,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(46,7,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(47,7,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(48,7,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(49,7,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(50,8,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(51,8,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(52,8,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(53,8,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(54,8,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(55,8,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(56,8,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(57,9,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(58,9,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(59,9,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(60,9,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(61,9,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(62,9,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(63,9,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(64,10,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(65,10,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(66,10,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(67,10,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(68,10,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(69,10,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(70,10,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(71,11,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(72,11,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(73,11,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(74,11,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(75,11,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(76,11,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(77,11,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(78,12,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(79,12,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(80,12,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(81,12,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(82,12,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(83,12,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(84,12,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(85,13,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(86,13,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(87,13,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(88,13,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(89,13,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(90,13,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(91,13,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(92,14,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(93,14,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(94,14,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(95,14,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(96,14,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(97,14,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(98,14,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(99,15,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(100,15,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(101,15,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(102,15,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(103,15,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(104,15,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(105,15,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(106,16,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(107,16,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(108,16,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(109,16,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(110,16,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(111,16,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(112,16,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(113,17,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(114,17,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(115,17,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(116,17,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(117,17,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(118,17,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(119,17,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(120,18,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(121,18,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(122,18,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(123,18,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(124,18,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(125,18,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(126,18,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(127,19,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(128,19,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(129,19,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(130,19,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(131,19,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(132,19,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(133,19,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(134,20,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(135,20,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(136,20,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(137,20,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(138,20,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(139,20,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(140,20,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(141,21,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(142,21,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(143,21,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(144,21,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(145,21,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(146,21,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(147,21,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(148,22,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(149,22,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(150,22,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(151,22,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(152,22,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(153,22,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(154,22,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(155,23,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(156,23,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(157,23,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(158,23,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(159,23,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(160,23,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(161,23,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(162,24,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(163,24,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(164,24,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(165,24,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(166,24,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(167,24,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(168,24,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(169,25,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(170,25,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(171,25,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(172,25,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(173,25,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(174,25,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(175,25,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(176,26,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(177,26,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(178,26,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(179,26,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(180,26,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(181,26,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(182,26,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(183,27,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(184,27,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(185,27,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(186,27,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(187,27,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(188,27,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(189,27,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(190,28,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(191,28,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(192,28,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(193,28,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(194,28,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(195,28,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(196,28,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(197,30,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(198,30,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(199,30,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(200,30,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(201,30,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(202,30,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(203,30,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(204,32,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(205,32,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(206,32,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(207,32,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(208,32,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(209,32,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(210,32,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(211,33,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(212,33,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(213,33,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(214,33,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(215,33,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(216,33,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(217,33,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(218,34,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(219,34,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(220,34,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(221,34,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(222,34,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(223,34,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(224,34,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(225,35,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(226,35,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(227,35,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(228,35,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(229,35,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(230,35,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(231,35,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(232,36,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(233,36,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(234,36,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(235,36,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(236,36,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(237,36,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(238,36,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(239,37,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(240,37,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(241,37,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(242,37,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(243,37,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(244,37,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(245,37,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(246,38,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(247,38,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(248,38,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(249,38,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(250,38,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(251,38,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(252,38,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(253,39,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(254,39,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(255,39,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(256,39,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(257,39,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(258,39,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(259,39,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(260,40,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(261,40,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(262,40,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(263,40,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(264,40,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(265,40,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(266,40,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(267,41,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(268,41,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(269,41,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(270,41,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(271,41,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(272,41,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(273,41,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(274,42,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(275,42,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(276,42,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(277,42,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(278,42,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(279,42,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(280,42,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(281,43,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(282,43,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(283,43,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(284,43,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(285,43,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(286,43,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(287,43,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(288,44,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(289,44,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(290,44,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(291,44,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(292,44,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(293,44,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(294,44,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(295,45,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(296,45,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(297,45,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(298,45,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(299,45,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(300,45,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(301,45,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(302,46,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(303,46,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(304,46,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(305,46,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(306,46,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(307,46,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(308,46,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(309,47,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(310,47,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(311,47,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(312,47,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(313,47,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(314,47,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(315,47,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(316,48,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(317,48,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(318,48,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(319,48,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(320,48,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(321,48,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(322,48,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(323,49,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(324,49,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(325,49,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(326,49,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(327,49,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(328,49,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(329,49,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(330,50,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(331,50,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(332,50,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(333,50,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(334,50,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(335,50,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(336,50,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(337,51,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(338,51,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(339,51,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(340,51,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(341,51,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(342,51,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(343,51,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(344,52,'99','All other (Vehicles not rated under a discount program)');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(345,52,'01','Vehicles with no discount but rated under a discount program');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(346,52,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(347,52,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(348,52,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(349,52,'05','Vehicles with an alarm and an active device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(350,52,'06','Vehicles with an alarm and a passive device — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(351,31,'10','Vehicles with VIN etched window glass only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(352,31,'11','With discount less than the maximum reduction of 25% per vehicle');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(353,31,'12','With discount equal to the maximum reduction of 25% per vehicle');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(354,31,'01','Vehicles with no discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(355,31,'02','Vehicles with alarm only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(356,31,'03','Vehicles with active devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(357,31,'04','Vehicles with passive devices — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(358,31,'05','Vehicles with electronic homing devices only — with discount');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(359,29,'01','Vehicle qualifies for discount under Category I');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(360,29,'02','Vehicle qualifies for discount under Category II');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(361,29,'03','Vehicle qualifies for discount under Category III');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(362,29,'04','Vehicle qualifies for discount under Category IV');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(363,29,'05','Vehicle qualifies for discount under Category III and IV');
    INSERT INTO ca_anti_theft_device_discount_code VALUES(364,29,'09','Vehicle without an anti-theft device (no discount)');

END IF;

END $$

