create table openidl_base_1234.pa_policy
    (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    naic_lob VARCHAR, -- aslob varchar
    openidl_lob VARCHAR,  --56? currently both CA & PA are 56, maybe we make 2 new ones?
    subline_name VARCHAR,
    subline_code varchar,
    subline_category VARCHAR,
    record_type VARCHAR,  --premium/oss
    transaction_type VARCHAR,
    transaction_code  VARCHAR,
    accounting_date DATE,
    company_code VARCHAR,
    company_id VARCHAR,
    state VARCHAR,
    state_code varchar,
    territory VARCHAR,  --maybe should be territory code
    optional_zip_code_indicator VARCHAR,
    premium_amount Numeric (20,6),
    program VARCHAR,
    program_code varchar,
    effective_date DATE,
    expiration_date DATE,
    policy_identifier VARCHAR,
    accounting_term_expiration DATE,
    nc_program_enhancement VARCHAR,
    zip_code VARCHAR,
    zip_code_suffix VARCHAR,
    monthly_premium_amount Numeric (20,6),
    coverage_category VARCHAR,
    coverage VARCHAR,
    coverage_code VARCHAR,
    liability_limits_name VARCHAR,
    liability_limits_amount VARCHAR ,
    deductible_code VARCHAR,
    deductible_amount VARCHAR,
    exposure Numeric (20,6),
    months_covered Numeric (20,6),
    single_multi_car_rating VARCHAR,
    terrorism VARCHAR,
    packaging VARCHAR,
    pool_affiliation VARCHAR,
    umuim_stacking VARCHAR,
    passive_restraint_discount VARCHAR,
    anti_lock_brakes_discount VARCHAR,
    defensive_driver_discount VARCHAR,
    operator_age VARCHAR,
    operator_age_code VARCHAR,
    gender VARCHAR,
    marital_status VARCHAR,
    marital_status_code VARCHAR,
    principal_secondary VARCHAR,
    drivers_training VARCHAR,
    good_student_discount VARCHAR,
    good_student_discount_code VARCHAR,
    penalty_points VARCHAR,
    penalty_points_code Varchar,
    vehicle_use_code varchar,
    vehicle_use VARCHAR,
    vehicle_use_operator VARCHAR,
    commute_distance VARCHAR,
    annual_distance VARCHAR,
    vehicle_performance VARCHAR,
    vehicle_performance_code VARCHAR,
    body_style VARCHAR,
    body_style_code VARCHAR,
    body_size VARCHAR,
    body_size_code VARCHAR,
    model_year Numeric (20,6),
    symbol VARCHAR
    );